query GetQuizSessions(
  $first: Int
  $after: String
  $where: QuizSessionFilterInput
  $order: [QuizSessionSortInput!]
) {
  quizSessions(first: $first, after: $after, where: $where, order: $order) {
    edges {
      cursor
      node {
        id
        title {
          id
          value
        }
        name
        email
        invitationSent
        resultsSent
        status
        numberOfQuestions
        maxTimeInMinutes
        startedAt
        completedAt
        score
        percentage
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
