#!/usr/bin/env node
// Generates provider-specific AI configuration from the provider-neutral sources.
//
//   Sources (edit these)              Generated (never edit by hand)
//   AGENTS.md                         .github/copilot-instructions.md
//   .ai/instructions/*.md             .github/instructions/*, .claude/rules/*
//   .ai/agents/*.md                   .github/agents/*, .claude/agents/*, .codex/agents/*.toml
//   .agents/skills/**                 .claude/skills/** (Copilot and Codex read .agents/skills natively)
//   .ai/hooks/guards.mjs              .github/hooks/guards.json, .codex/hooks.json, hooks key of .claude/settings.json
//   .ai/providers.json                model tiers and tool mapping per host
//
// Usage: node .ai/scripts/sync.mjs [--check]
//   --check  write nothing; exit 1 if any generated file is missing or out of date (use in CI).
//
// Zero dependencies; requires Node 18+.

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, rmdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const checkOnly = process.argv.includes("--check");
const providers = JSON.parse(readFileSync(path.join(root, ".ai/providers.json"), "utf8"));

const outputs = new Map(); // repo-relative posix path -> string | Buffer
const managedDirs = []; // directories whose stale managed entries are cleaned up
const problems = [];

const rel = (...parts) => parts.join("/");
const abs = (relativePath) => path.join(root, ...relativePath.split("/"));
const lf = (text) => text.replace(/\r\n/g, "\n");
const read = (relativePath) => lf(readFileSync(abs(relativePath), "utf8"));

function listFiles(dir) {
  const full = abs(dir);
  if (!existsSync(full)) return [];
  const result = [];
  for (const entry of readdirSync(full, { withFileTypes: true })) {
    const child = rel(dir, entry.name);
    if (entry.isDirectory()) result.push(...listFiles(child));
    else result.push(child);
  }
  return result.sort();
}

function parseFrontmatter(text, source) {
  const match = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(lf(text));
  if (!match) {
    problems.push(`${source}: missing YAML frontmatter`);
    return { meta: {}, body: text };
  }
  const meta = {};
  for (const line of match[1].split("\n")) {
    const pair = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
    if (!pair) continue;
    let value = pair[2].trim();
    if (/^(".*"|'.*')$/.test(value)) value = value.slice(1, -1);
    meta[pair[1]] = value;
  }
  return { meta, body: match[2].replace(/^\n+/, "") };
}

const yamlScalar = (value) =>
  /^[\s\-?:,\[\]{}#&*!|>'"%@`]|: | #|\s$/.test(value) ? JSON.stringify(value) : value;

const marker = (source) =>
  `<!-- GENERATED by .ai/scripts/sync.mjs from ${source}. Do not edit; change the source and re-run the script. -->`;

function tierModel(host, tierName, field, owner) {
  const tier = providers[host]?.tiers?.[tierName];
  if (!tier) {
    problems.push(`${owner}: tier "${tierName}" is not defined for ${host} in providers.json`);
    return null;
  }
  if (tier[field] === undefined) {
    problems.push(`${owner}: providers.json ${host}.tiers.${tierName}.${field} is missing (use null to inherit)`);
    return null;
  }
  return tier[field];
}

// ---------------------------------------------------------------- instructions
function generateInstructions() {
  const files = listFiles(".ai/instructions").filter((file) => file.endsWith(".instructions.md"));
  for (const file of files) {
    const { meta, body } = parseFrontmatter(read(file), file);
    if (!meta.applyTo) {
      problems.push(`${file}: missing applyTo`);
      continue;
    }
    const name = path.posix.basename(file);

    // GitHub Copilot: applyTo frontmatter, identical to the neutral form.
    outputs.set(
      rel(".github/instructions", name),
      `---\napplyTo: ${JSON.stringify(meta.applyTo)}\n---\n\n${marker(file)}\n\n${body}`,
    );

    // Claude Code: .claude/rules with a paths list.
    const globs = meta.applyTo.split(",").map((glob) => glob.trim()).filter(Boolean);
    outputs.set(
      rel(".claude/rules", name.replace(/\.instructions\.md$/, ".md")),
      `---\npaths:\n${globs.map((glob) => `  - ${JSON.stringify(glob)}`).join("\n")}\n---\n\n${marker(file)}\n\n${body}`,
    );
  }
  managedDirs.push(".github/instructions", ".claude/rules");
}

// ---------------------------------------------------------------- agents
function generateAgents() {
  const files = listFiles(".ai/agents").filter((file) => file.endsWith(".md"));
  for (const file of files) {
    const { meta, body } = parseFrontmatter(read(file), file);
    for (const key of ["name", "description", "access", "model-tier"]) {
      if (!meta[key]) problems.push(`${file}: missing ${key}`);
    }
    if (!meta.name || !meta.description || !meta.access || !meta["model-tier"]) continue;

    // GitHub Copilot custom agent.
    const copilotTools = providers.copilot.accessTools[meta.access];
    const copilotModel = tierModel("copilot", meta["model-tier"], "agentModel", file);
    if (!copilotTools) problems.push(`${file}: unknown access "${meta.access}" for copilot`);
    outputs.set(
      rel(".github/agents", `${meta.name}.agent.md`),
      [
        "---",
        `name: ${yamlScalar(meta.name)}`,
        `description: ${yamlScalar(meta.description)}`,
        ...(copilotModel ? [`model: ${yamlScalar(copilotModel)}`] : []),
        "include-custom-instructions: true",
        "tools:",
        ...(copilotTools ?? []).map((tool) => `  - ${tool}`),
        "---",
        "",
        marker(file),
        "",
        body,
      ].join("\n"),
    );

    // Claude Code subagent.
    const claudeTools = providers.claude.accessTools[meta.access];
    const claudeModel = tierModel("claude", meta["model-tier"], "agentModel", file);
    if (!claudeTools) problems.push(`${file}: unknown access "${meta.access}" for claude`);
    outputs.set(
      rel(".claude/agents", `${meta.name}.md`),
      [
        "---",
        `name: ${yamlScalar(meta.name)}`,
        `description: ${yamlScalar(meta.description)}`,
        `tools: ${(claudeTools ?? []).join(", ")}`,
        ...(claudeModel ? [`model: ${yamlScalar(claudeModel)}`] : []),
        "---",
        "",
        marker(file),
        "",
        body,
      ].join("\n"),
    );

    // Codex custom agent (TOML). Access maps to a sandbox mode.
    const sandbox = providers.codex.accessSandbox[meta.access];
    const codexModel = tierModel("codex", meta["model-tier"], "agentModel", file);
    if (!sandbox) problems.push(`${file}: unknown access "${meta.access}" for codex`);
    if (body.includes("'''")) problems.push(`${file}: body contains ''' which cannot be embedded in TOML`);
    outputs.set(
      rel(".codex/agents", `${meta.name}.toml`),
      [
        `# GENERATED by .ai/scripts/sync.mjs from ${file}. Do not edit; change the source and re-run the script.`,
        `name = ${JSON.stringify(meta.name)}`,
        `description = ${JSON.stringify(meta.description)}`,
        ...(sandbox ? [`sandbox_mode = ${JSON.stringify(sandbox)}`] : []),
        ...(codexModel ? [`model = ${JSON.stringify(codexModel)}`] : []),
        `developer_instructions = '''`,
        body.trimEnd(),
        `'''`,
        "",
      ].join("\n"),
    );
  }
  managedDirs.push(".github/agents", ".claude/agents", ".codex/agents");
}

// ---------------------------------------------------------------- skills
const skillMarkerFile = ".claude/skills/.managed-by-sync";

function generateSkills() {
  const files = listFiles(".agents/skills");
  const names = new Set();
  for (const file of files) {
    const inner = file.slice(".agents/skills/".length);
    names.add(inner.split("/")[0]);
    const content = readFileSync(abs(file));
    // Text files are compared with normalised line endings; binaries byte for byte.
    outputs.set(rel(".claude/skills", inner), /\.(md|txt|json|ya?ml|mjs|js|ts|py|sh|toml)$/i.test(inner) ? lf(content.toString("utf8")) : content);
  }
  outputs.set(skillMarkerFile, `${[...names].sort().join("\n")}\n`);
}

// ---------------------------------------------------------------- hooks
const guard = ".ai/hooks/guards.mjs";

function generateHooks() {
  // GitHub Copilot. No `|| true` / `exit 0`: a failing guard must not be swallowed.
  outputs.set(
    ".github/hooks/guards.json",
    `${JSON.stringify(
      {
        version: 1,
        hooks: {
          preToolUse: [
            {
              type: "command",
              matcher: "view|read|edit|create|str_replace_editor|apply_patch|bash|powershell|create_pull_request|update_pull_request",
              bash: `node ${guard} pre --provider=copilot`,
              powershell: `node ${guard} pre --provider=copilot`,
              cwd: ".",
              timeoutSec: 10,
            },
          ],
          postToolUse: [
            {
              type: "command",
              matcher: "edit|apply_patch|str_replace_editor|bash|powershell",
              bash: `node ${guard} post --provider=copilot`,
              powershell: `node ${guard} post --provider=copilot`,
              cwd: ".",
              timeoutSec: 10,
            },
          ],
        },
      },
      null,
      2,
    )}\n`,
  );

  // Codex CLI hooks (requires the codex hooks feature to be enabled; see .ai/README.md).
  const codexGroup = (event, matcher) => ({
    matcher,
    hooks: [{ type: "command", command: `node ${guard} ${event} --provider=codex`, timeout: 10 }],
  });
  outputs.set(
    ".codex/hooks.json",
    `${JSON.stringify(
      {
        hooks: {
          PreToolUse: [codexGroup("pre", "Bash|apply_patch|Edit|Write|Read")],
          PostToolUse: [codexGroup("post", "Bash|apply_patch|Edit|Write")],
        },
      },
      null,
      2,
    )}\n`,
  );

  // Claude Code: merge into .claude/settings.json, keeping every unrelated setting and hook.
  const claudeCommand = (event) => `node "$CLAUDE_PROJECT_DIR/${guard}" ${event} --provider=claude`;
  const ours = {
    PreToolUse: {
      matcher: "Read|Edit|MultiEdit|Write|NotebookEdit|Bash|mcp__.*__(create|update)_pull_request",
      hooks: [{ type: "command", command: claudeCommand("pre"), timeout: 10 }],
    },
    PostToolUse: {
      matcher: "Edit|MultiEdit|Write|NotebookEdit|Bash",
      hooks: [{ type: "command", command: claudeCommand("post"), timeout: 10 }],
    },
  };
  let settings = {};
  if (existsSync(abs(".claude/settings.json"))) {
    try {
      settings = JSON.parse(read(".claude/settings.json"));
    } catch (error) {
      problems.push(`.claude/settings.json is not valid JSON, refusing to overwrite it: ${error.message}`);
      return;
    }
  }
  settings.hooks ??= {};
  for (const [event, group] of Object.entries(ours)) {
    const others = (settings.hooks[event] ?? []).filter(
      (existing) => !(existing.hooks ?? []).some((hook) => String(hook.command ?? "").includes("guards.mjs")),
    );
    settings.hooks[event] = [...others, group];
  }
  outputs.set(".claude/settings.json", `${JSON.stringify(settings, null, 2)}\n`);
}

// ---------------------------------------------------------------- copilot repo instructions
function generateCopilotInstructions() {
  const mode = providers.copilot.instructionsMode ?? "pointer";
  if (mode === "copy") {
    outputs.set(".github/copilot-instructions.md", `${marker("AGENTS.md")}\n\n${read("AGENTS.md")}`);
  } else {
    outputs.set(
      ".github/copilot-instructions.md",
      `${marker("AGENTS.md")}\n\n# Repository Copilot instructions\n\nThe canonical instructions for this repository are in \`AGENTS.md\` at the repository root. Read and follow that file first; it applies in full to Copilot (plan gate, invariants, build and test commands, token hygiene).\n`,
    );
  }
}

// ---------------------------------------------------------------- run
generateInstructions();
generateAgents();
generateSkills();
generateHooks();
generateCopilotInstructions();

if (problems.length > 0) {
  console.error(`sync: ${problems.length} problem(s):\n- ${problems.join("\n- ")}`);
  process.exit(2);
}

const same = (relativePath, wanted) => {
  if (!existsSync(abs(relativePath))) return false;
  const current = readFileSync(abs(relativePath));
  return typeof wanted === "string" ? lf(current.toString("utf8")) === wanted : current.equals(wanted);
};

// Stale managed files: generated files whose source was removed.
const stale = [];
for (const dir of managedDirs) {
  for (const file of listFiles(dir)) {
    if (outputs.has(file)) continue;
    // Only touch files that carry our marker, so hand-written siblings survive.
    const head = readFileSync(abs(file), "utf8").slice(0, 400);
    if (head.includes("GENERATED by .ai/scripts/sync.mjs")) stale.push(file);
  }
}
if (existsSync(abs(skillMarkerFile))) {
  const previous = lf(readFileSync(abs(skillMarkerFile), "utf8")).split("\n").filter(Boolean);
  const current = new Set(outputs.get(skillMarkerFile).split("\n").filter(Boolean));
  for (const name of previous) {
    if (current.has(name)) continue;
    for (const file of listFiles(rel(".claude/skills", name))) stale.push(file);
  }
}

const drift = [...outputs].filter(([file, content]) => !same(file, content)).map(([file]) => file);

if (checkOnly) {
  const issues = [...drift.map((file) => `out of date: ${file}`), ...stale.map((file) => `stale: ${file}`)];
  if (issues.length > 0) {
    console.error(`sync --check: generated files are not in sync with their sources:\n- ${issues.join("\n- ")}\nRun: node .ai/scripts/sync.mjs`);
    process.exit(1);
  }
  console.log(`sync --check: ${outputs.size} generated files are up to date.`);
} else {
  for (const [file, content] of outputs) {
    if (same(file, content)) continue;
    mkdirSync(path.dirname(abs(file)), { recursive: true });
    writeFileSync(abs(file), content);
  }
  for (const file of stale) {
    rmSync(abs(file), { force: true });
    // Remove directories left empty by the removal (never above the host config directories).
    for (let dir = path.posix.dirname(file); dir.split("/").length > 2; dir = path.posix.dirname(dir)) {
      if (readdirSync(abs(dir)).length > 0) break;
      rmdirSync(abs(dir));
    }
  }
  console.log(`sync: ${drift.length} written, ${outputs.size - drift.length} unchanged, ${stale.length} stale removed.`);
}
