#!/usr/bin/env node
// Fixed native adapters; validate shared config without changing host settings.
import { createHash } from "node:crypto";
import { lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadModelConfig } from "./resolve-model.mjs";

const script = fileURLToPath(import.meta.url);
const defaultRoot = path.resolve(path.dirname(script), "../..");
const owner = "GENERATED by .ai/scripts/sync.mjs";
const marker = (source) => `<!-- ${owner} from ${source}. Do not edit; change the source and re-run the script. -->`;
const lf = (text) => text.replace(/\r\n/g, "\n");
const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
const manifestName = ".managed-by-sync.json";

function frontmatter(text, source) {
  const match = /^(---\n)([\s\S]*?)(\n---\n)([\s\S]*)$/.exec(text);
  if (!match) throw new Error(`${source}: missing YAML frontmatter`);
  return { header: match[2], body: match[4] };
}

function markdown(text, source, header) {
  if (text.startsWith("---\n")) {
    const parsed = frontmatter(text, source);
    return `---\n${header ?? parsed.header}\n---\n\n${marker(source)}\n\n${parsed.body.trimStart()}`;
  }
  return `${marker(source)}\n\n${text}`;
}

function ownsMarkdown(bytes) {
  const text = lf(bytes.toString("utf8"));
  const body = text.startsWith("---\n") ? /^---\n[\s\S]*?\n---\n([\s\S]*)$/.exec(text)?.[1] ?? "" : text;
  return body.trimStart().startsWith(`<!-- ${owner} from `);
}

/**
 * Generate the complete adapter set, or report drift without writing.
 * A fixture root must contain the same canonical sources as the repository.
 * Source errors, collisions, and obsolete owned outputs prevent every write.
 */
export function sync(root = defaultRoot, { check = false } = {}) {
  root = realpathSync(root);
  // Reject symlinks (even internal ones), special files, and traversal before I/O.
  function safe(relative) {
    const parts = relative.split("/");
    if (parts.some((part) => !part || /[. ]$|[<>:"|?*\\\x00-\x1f]/.test(part) ||
        /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(part))) {
      throw new Error(`unsafe path: ${relative}`);
    }
    let full = root;
    for (const [index, part] of parts.entries()) {
      full = path.join(full, part);
      let stat;
      try { stat = lstatSync(full); } catch (error) {
        if (error.code === "ENOENT") continue;
        throw error;
      }
      if (stat.isSymbolicLink() || (!stat.isDirectory() && !stat.isFile()) ||
          (index < parts.length - 1 && !stat.isDirectory()) ||
          (stat.isFile() && stat.nlink > 1)) {
        throw new Error(`unsafe file or ancestor: ${relative}`);
      }
    }
    return full;
  }
  function bytes(file) {
    const full = safe(file);
    if (!lstatSync(full).isFile()) throw new Error(`not a file: ${file}`);
    return readFileSync(full);
  }
  const text = (file) => lf(bytes(file).toString("utf8"));
  function exists(file) {
    try { lstatSync(safe(file)); return true; } catch (error) {
      if (error.code === "ENOENT") return false;
      throw error;
    }
  }
  function files(directory) {
    return readdirSync(safe(directory), { withFileTypes: true })
      .sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)
      .flatMap((entry) => {
        const file = `${directory}/${entry.name}`;
        safe(file);
        return entry.isDirectory() ? files(file) : [file];
      });
  }

  safe(".ai/models.json");
  loadModelConfig(root);

  const outputs = new Map();
  const resourceOwners = new Map();
  const manifests = new Set();
  const previousResources = [];
  function add(file, content) {
    safe(file);
    if (outputs.has(file)) throw new Error(`duplicate output: ${file}`);
    outputs.set(file, Buffer.isBuffer(content) ? content : Buffer.from(content));
  }
  text("AGENTS.md"); // A bridge without its canonical contract is not usable.
  add("CLAUDE.md", `${marker("AGENTS.md")}\n\n@AGENTS.md\n`);
  add(".github/copilot-instructions.md",
    `${marker("AGENTS.md")}\n\nRead and follow [AGENTS.md](../AGENTS.md) at the repository root. It is the canonical repository contract, including the approval gate and scoped-instruction table. Use the canonical skills in \`.agents/skills/\`; read the applicable shared instructions explicitly if this host does not load scoped rules.\n`);

  for (const name of ["backend", "ui", "workflows"]) {
    const source = `.ai/instructions/${name}.instructions.md`;
    const content = text(source);
    const { header } = frontmatter(content, source);
    if (!/^applyTo:[ \t]*\S/m.test(header)) throw new Error(`${source}: missing applyTo`);
    add(`.github/instructions/${name}.instructions.md`, markdown(content, source));
    // Claude accepts a YAML list or comma-separated scalar; preserve YAML verbatim.
    add(`.claude/rules/${name}.md`, markdown(content, source, header.replace(/^applyTo:/m, "paths:")));
  }

  for (const [name, template] of [["audit", "template.md"], ["deliver", "plan-template.md"]]) {
    const source = `.agents/skills/${name}`;
    for (const required of ["SKILL.md", template]) {
      if (!exists(`${source}/${required}`)) {
        throw new Error(`missing required source: ${source}/${required}; restore canonical skills before full sync (WP-03)`);
      }
    }
    const { header } = frontmatter(text(`${source}/SKILL.md`), `${source}/SKILL.md`);
    for (const key of ["name", "description"]) {
      if (!new RegExp(`^${key}:[ \\t]*\\S`, "m").test(header)) throw new Error(`${source}/SKILL.md: missing ${key}`);
    }
    const destination = `.claude/skills/${name}`;
    const manifest = `${destination}/${manifestName}`;
    let previous = {};
    if (exists(manifest)) {
      previous = JSON.parse(text(manifest));
      if (previous.generatedBy !== owner || !previous.resources ||
          typeof previous.resources !== "object" || Array.isArray(previous.resources)) {
        throw new Error(`unowned output: ${manifest}`);
      }
      for (const [inner, digest] of Object.entries(previous.resources)) {
        safe(`${destination}/${inner}`);
        if (!/^[a-f0-9]{64}$/.test(digest)) throw new Error(`invalid resource ownership: ${manifest}`);
        previousResources.push(`${destination}/${inner}`);
      }
    }
    manifests.add(manifest);
    const resources = Object.create(null);
    for (const file of files(source)) {
      const inner = file.slice(source.length + 1);
      if (inner === manifestName) throw new Error(`reserved resource name: ${file}`);
      const target = `${destination}/${inner}`;
      const content = bytes(file);
      if (/\.md$/i.test(inner)) {
        // Both skill trees have identical depth: sibling resources and repository
        // references stay valid without rewriting Markdown or native frontmatter.
        add(target, markdown(lf(content.toString("utf8")), file));
      } else {
        add(target, content);
        resources[inner] = hash(content);
        resourceOwners.set(target, previous.resources?.[inner]);
      }
    }
    add(manifest, `${JSON.stringify({ generatedBy: owner, resources }, null, 2)}\n`);
  }

  const issue = ".ai/templates/issue.md";
  add(".github/ISSUE_TEMPLATE/work-item.md",
    `---\nname: Work item\nabout: Request a feature, report a defect, or describe approved follow-up work.\ntitle: ""\nlabels: ""\nassignees: ""\n---\n\n${markdown(text(issue), issue)}`);
  const pr = ".ai/templates/pull-request.md";
  add(".github/pull_request_template.md", markdown(text(pr), pr));

  const issues = [];
  const changed = [];
  // Preflight the entire output set before mkdir/write, including late collisions.
  for (const [file, wanted] of outputs) {
    if (!exists(file)) {
      issues.push(`missing output: ${file}`);
      changed.push(file);
      continue;
    }
    const current = bytes(file);
    const owned = manifests.has(file) ||
      (resourceOwners.has(file) ? resourceOwners.get(file) === hash(current) : ownsMarkdown(current));
    const matches = resourceOwners.has(file)
      ? current.equals(wanted)
      : lf(current.toString("utf8")) === lf(wanted.toString("utf8"));
    if (!owned) issues.push(`unowned output: ${file}`);
    else if (!matches) {
      issues.push(`stale output: ${file}`);
      changed.push(file);
    }
  }
  const managed = [".github/instructions", ".claude/rules", ".claude/skills/audit", ".claude/skills/deliver"];
  const obsolete = new Set(previousResources.filter((file) => !outputs.has(file) && exists(file)));
  for (const directory of managed) {
    if (!exists(directory)) continue;
    for (const file of files(directory)) {
      if (!outputs.has(file) && /\.md$/i.test(file) && ownsMarkdown(bytes(file))) obsolete.add(file);
    }
  }
  for (const file of [...obsolete].sort()) issues.push(`obsolete owned output (not deleted): ${file}`);
  issues.sort();
  if (check) return { issues, written: 0, total: outputs.size };
  const blockers = issues.filter((issue) => !/^(missing|stale) output:/.test(issue));
  if (blockers.length) throw new Error(blockers.join("\n"));
  for (const file of changed) {
    const full = safe(file);
    mkdirSync(path.dirname(full), { recursive: true });
    writeFileSync(full, outputs.get(file));
  }
  return { issues: [], written: changed.length, total: outputs.size };
}

if (process.argv[1] && path.resolve(process.argv[1]) === script) {
  try {
    const args = process.argv.slice(2);
    if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
      throw new Error("usage: node .ai/scripts/sync.mjs [--check]");
    }
    const result = sync(defaultRoot, { check: args[0] === "--check" });
    if (result.issues.length) {
      console.error(result.issues.join("\n"));
      process.exitCode = 1;
    } else console.log(`sync: ${result.total} outputs, ${result.written} written`);
  } catch (error) {
    console.error(`sync: ${error.message}`);
    process.exitCode = 2;
  }
}
