import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  closeSync, constants, cpSync, existsSync, fstatSync, linkSync, lstatSync, mkdirSync, mkdtempSync,
  openSync, readFileSync, readdirSync, readlinkSync, renameSync, rmSync, symlinkSync, writeFileSync,
} from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { sync } from "../.ai/scripts/sync.mjs";
import { loadModelConfig, resolveModel } from "../.ai/scripts/resolve-model.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const owner = "GENERATED by .ai/scripts/sync.mjs";
const expectedOutputs = [
  "CLAUDE.md",
  ".github/copilot-instructions.md",
  ".github/instructions/backend.instructions.md",
  ".github/instructions/ui.instructions.md",
  ".github/instructions/workflows.instructions.md",
  ".claude/rules/backend.md",
  ".claude/rules/ui.md",
  ".claude/rules/workflows.md",
  ".claude/skills/audit/SKILL.md",
  ".claude/skills/audit/template.md",
  ".claude/skills/audit/.managed-by-sync.json",
  ".claude/skills/deliver/SKILL.md",
  ".claude/skills/deliver/plan-template.md",
  ".claude/skills/deliver/.managed-by-sync.json",
  ".github/ISSUE_TEMPLATE/work-item.md",
  ".github/pull_request_template.md",
].sort();
const scopes = {
  backend: "**/*.cs",
  ui: "RefTestManagement.Ui/**",
  workflows: ".github/workflows/**",
};
const read = (base, file) => readFileSync(path.join(base, file), "utf8").replace(/\r\n/g, "\n");
const digest = (bytes) => createHash("sha256").update(bytes).digest("hex");

function write(base, file, content) {
  const target = path.join(base, file);
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, content);
}

function fixture(t) {
  // Keep isolated, disposable fixtures inside the checkout, never in the OS temp directory.
  const base = mkdtempSync(path.join(root, "tests", ".ai-workflow-"));
  t.after(() => rmSync(base, { recursive: true, force: true }));
  for (const file of ["AGENTS.md", "README.md", ".ai", ".agents"]) {
    cpSync(path.join(root, file), path.join(base, file), { recursive: true });
  }
  write(base, ".ai/models.json", JSON.stringify(Object.fromEntries(modelProviders.map((provider) => [
    provider, { default: null, agents: Object.fromEntries(modelAgents.map((agent) => [agent, null])) },
  ]))));
  return base;
}

function snapshotFile(file, expected) {
  const descriptor = openSync(file, constants.O_RDONLY | (constants.O_NOFOLLOW ?? 0));
  try {
    const stat = fstatSync(descriptor);
    assert.ok(stat.isFile() && stat.dev === expected.dev && stat.ino === expected.ino,
      "snapshot file changed after lstat");
    return {
      mode: stat.mode,
      mtime: stat.mtimeMs,
      content: readFileSync(descriptor).toString("base64"),
    };
  } finally {
    closeSync(descriptor);
  }
}

function snapshot(base) {
  const result = {};
  function visit(directory) {
    for (const name of readdirSync(directory).sort()) {
      const file = path.join(directory, name);
      const stat = lstatSync(file);
      const relative = path.relative(base, file).split(path.sep).join("/");
      result[relative] = stat.isFile() ? snapshotFile(file, stat) : {
        mode: stat.mode,
        mtime: stat.mtimeMs,
        content: stat.isSymbolicLink() ? readlinkSync(file) : null,
      };
      if (stat.isDirectory() && !stat.isSymbolicLink()) visit(file);
    }
  }
  visit(base);
  return result;
}

function header(content) {
  const match = /^---\n([\s\S]+?)\n---\n/.exec(content);
  assert.ok(match, "native YAML frontmatter must be first");
  return match[1];
}

function withoutMarker(content) {
  return content.replace(/<!-- GENERATED by \.ai\/scripts\/sync\.mjs from [^\n]+ -->\n\n/, "");
}

function cli(base, args, cwd = base, script = "sync.mjs") {
  const result = spawnSync(process.execPath, [path.join(base, ".ai", "scripts", script), ...args], {
    cwd, encoding: "utf8", timeout: 15_000,
  });
  assert.ifError(result.error);
  assert.equal(result.signal, null);
  return result;
}

const modelProviders = ["claude", "codex", "github-copilot"];
const modelAgents = ["implementer", "auditor", "reviewer"];

test("snapshot preserves regular-file binary content and descriptor metadata", (t) => {
  const base = fixture(t);
  const file = path.join(base, "binary.dat");
  const content = Buffer.from([0, 255, 128, 13, 10]);
  writeFileSync(file, content);
  const stat = lstatSync(file);

  assert.deepEqual(snapshot(base)["binary.dat"], {
    mode: stat.mode,
    mtime: stat.mtimeMs,
    content: content.toString("base64"),
  });
});

test("snapshot rejects a different file replacing the checked pathname", (t) => {
  const base = fixture(t);
  const file = path.join(base, "original.dat");
  writeFileSync(file, "original");
  const stat = lstatSync(file);
  renameSync(file, path.join(base, "retained.dat"));
  writeFileSync(file, "replacement");

  assert.throws(() => snapshotFile(file, stat), /snapshot file changed after lstat/);
});

test("repository model preferences resolve for every provider and agent", () => {
  const config = loadModelConfig(root);
  for (const provider of modelProviders) {
    for (const agent of modelAgents) {
      assert.deepEqual(resolveModel(root, provider, agent), {
        provider, agent, model: config[provider].agents[agent] ?? config[provider].default,
      });
    }
  }
});

for (const provider of modelProviders) {
  for (const agent of modelAgents) {
    test(`model precedence for ${provider}/${agent}: user, role, provider, host`, (t) => {
      const base = fixture(t);
      const config = loadModelConfig(base);
      for (const entry of Object.values(config)) {
        entry.default = null;
        for (const role of modelAgents) entry.agents[role] = null;
      }
      write(base, ".ai/models.json", JSON.stringify(config));
      assert.equal(resolveModel(base, provider, agent).model, null);
      config[provider].default = "default-model";
      write(base, ".ai/models.json", JSON.stringify(config));
      assert.equal(resolveModel(base, provider, agent).model, "default-model");
      config[provider].agents[agent] = "vendor/role-model:latest";
      write(base, ".ai/models.json", JSON.stringify(config));
      const before = snapshot(base);
      assert.equal(resolveModel(base, provider, agent).model, "vendor/role-model:latest");
      assert.equal(resolveModel(base, provider, agent, { override: "user-model" }).model, "user-model");
      assert.equal(resolveModel(base, provider, agent, { override: null }).model, null);
      for (const other of modelProviders.filter((value) => value !== provider)) {
        assert.equal(resolveModel(base, other, agent).model, null);
      }
      for (const other of modelAgents.filter((value) => value !== agent)) {
        assert.equal(resolveModel(base, provider, other).model, "default-model");
      }
      assert.deepEqual(snapshot(base), before);
    });
  }
}

for (const [name, change, error] of [
  ["missing provider", (c) => { delete c.claude; }, /missing claude/],
  ["unknown provider", (c) => { c.other = c.claude; }, /unknown key other/],
  ["non-object provider", (c) => { c.codex = []; }, /codex: expected an object/],
  ["missing default", (c) => { delete c.claude.default; }, /missing default/],
  ["unknown provider field", (c) => { c.claude.model = null; }, /unknown key model/],
  ["missing agents", (c) => { delete c.codex.agents; }, /missing agents/],
  ["non-object agents", (c) => { c.codex.agents = null; }, /codex.agents: expected an object/],
  ["missing agent", (c) => { delete c.codex.agents.reviewer; }, /missing reviewer/],
  ["unknown agent", (c) => { c.codex.agents.planner = null; }, /unknown key planner/],
  ["empty default", (c) => { c.claude.default = ""; }, /claude.default: expected null/],
  ["whitespace ID", (c) => { c.claude.agents.auditor = " model "; }, /claude.agents.auditor: expected null/],
  ["numeric ID", (c) => { c.codex.default = 7; }, /codex.default: expected null/],
  ["boolean ID", (c) => { c.codex.agents.implementer = false; }, /codex.agents.implementer: expected null/],
  ["object ID", (c) => { c["github-copilot"].default = {}; }, /github-copilot.default: expected null/],
  ["control character", (c) => { c["github-copilot"].agents.reviewer = "model\n"; }, /github-copilot.agents.reviewer: expected null/],
  ["command-like ID", (c) => { c.claude.default = "--model=oops"; }, /claude.default: expected null/],
]) {
  test(`invalid model config prevents all adapter writes: ${name}`, (t) => {
    const base = fixture(t);
    sync(base);
    write(base, ".ai/instructions/ui.instructions.md", `${read(base, ".ai/instructions/ui.instructions.md")}\nChanged.\n`);
    const config = loadModelConfig(base);
    change(config);
    write(base, ".ai/models.json", JSON.stringify(config));
    const before = snapshot(base);
    assert.throws(() => resolveModel(base, "github-copilot", "reviewer", { override: "user-model" }), error);
    assert.throws(() => sync(base), error);
    assert.throws(() => sync(base, { check: true }), error);
    assert.deepEqual(snapshot(base), before);
  });
}

for (const [content, error] of [
  [null, /ENOENT/],
  ["{", /invalid JSON/],
  ["null", /expected an object/],
  ["[]", /expected an object/],
  ['"value"', /expected an object/],
]) {
  test(`missing or malformed model config is an error: ${content}`, (t) => {
    const base = fixture(t);
    if (content === null) rmSync(path.join(base, ".ai/models.json"));
    else write(base, ".ai/models.json", content);
    const before = snapshot(base);
    assert.throws(() => loadModelConfig(base), error);
    assert.throws(() => sync(base), error);
    const result = cli(base, ["claude", "auditor"], root, "resolve-model.mjs");
    assert.equal(result.status, 2);
    assert.equal(result.stdout, "");
    assert.match(result.stderr, error);
    assert.deepEqual(snapshot(base), before);
  });
}

test("model CLI resolves its own root, emits only selection JSON, and rejects invalid requests", (t) => {
  const base = fixture(t);
  const config = loadModelConfig(base);
  config.claude.default = "claude-default";
  config.codex.agents.auditor = "codex-auditor";
  write(base, ".ai/models.json", JSON.stringify(config));
  const before = snapshot(base);
  for (const provider of modelProviders) {
    for (const agent of modelAgents) {
      const result = cli(base, [provider, agent], root, "resolve-model.mjs");
      assert.equal(result.status, 0, result.stderr);
      assert.equal(result.stderr, "");
      assert.deepEqual(JSON.parse(result.stdout), resolveModel(base, provider, agent));
    }
  }
  for (const args of [[], ["claude"], ["claude", "auditor", "extra"], ["Claude", "auditor"], ["other", "reviewer"], ["codex", "planner"]]) {
    const result = cli(base, args, root, "resolve-model.mjs");
    assert.equal(result.status, 2);
    assert.equal(result.stdout, "");
    assert.match(result.stderr, /usage:|unknown provider:|unknown agent:/);
  }
  for (const override of ["", "bad value", {}, false]) {
    assert.throws(() => resolveModel(base, "claude", "auditor", { override }), /explicit override: expected null/);
  }
  assert.deepEqual(snapshot(base), before);
});

test("model preference edits validate without changing native adapter outputs", (t) => {
  const base = fixture(t);
  sync(base);
  const config = loadModelConfig(base);
  config["github-copilot"].agents.reviewer = "selected-reviewer";
  write(base, ".ai/models.json", JSON.stringify(config));
  const before = snapshot(base);
  assert.deepEqual(sync(base), { issues: [], written: 0, total: 16 });
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 16 });
  assert.deepEqual(snapshot(base), before);
});

test("generates exactly the fixed native output set, without unused provider configuration", (t) => {
  const base = fixture(t);
  const before = snapshot(base);
  assert.deepEqual(sync(base), { issues: [], written: 16, total: 16 });
  const after = snapshot(base);
  const addedFiles = Object.keys(after).filter((file) => !before[file] && after[file].content !== null);
  assert.deepEqual(addedFiles.sort(), expectedOutputs);
  for (const [file, state] of Object.entries(before)) {
    if (state.content !== null) assert.deepEqual(after[file], state, `source changed: ${file}`);
  }
  assert.match(read(base, "CLAUDE.md"), /^<!-- GENERATED[^\n]+ -->\n\n@AGENTS\.md\n$/);
  assert.match(read(base, ".github/copilot-instructions.md"), /\[AGENTS\.md\]\(\.\.\/AGENTS\.md\)/);
});

test("preserves native skill metadata, source bodies and scope mappings", (t) => {
  const base = fixture(t);
  sync(base);
  for (const [name, scope] of Object.entries(scopes)) {
    const source = read(base, `.ai/instructions/${name}.instructions.md`);
    const copilot = read(base, `.github/instructions/${name}.instructions.md`);
    const claude = read(base, `.claude/rules/${name}.md`);
    assert.equal(header(source), `applyTo: "${scope}"`);
    assert.equal(header(copilot), header(source));
    assert.equal(header(claude), `paths: "${scope}"`);
    assert.equal(withoutMarker(copilot), source);
    assert.equal(withoutMarker(claude).replace("paths:", "applyTo:"), source);
    assert.match(read(base, "AGENTS.md"), new RegExp(scope.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  for (const [name, template] of [["audit", "template.md"], ["deliver", "plan-template.md"]]) {
    for (const file of ["SKILL.md", template]) {
      const source = read(base, `.agents/skills/${name}/${file}`);
      const generated = read(base, `.claude/skills/${name}/${file}`);
      assert.equal(withoutMarker(generated), source);
      if (file === "SKILL.md") {
        assert.equal(header(generated), header(source));
        assert.match(header(source), new RegExp(`^name: ${name}$`, "m"));
        assert.match(header(source), /^description: >-\n  \S/m);
        assert.ok(generated.indexOf(owner) > generated.indexOf("\n---\n"));
      }
    }
  }
  const issue = read(base, ".github/ISSUE_TEMPLATE/work-item.md");
  assert.equal(header(issue), 'name: Work item\nabout: Request a feature, report a defect, or describe approved follow-up work.\ntitle: ""\nlabels: ""\nassignees: ""');
  assert.equal(withoutMarker(issue.slice(issue.indexOf("\n---\n") + 5)).trimStart(), read(base, ".ai/templates/issue.md"));
  assert.equal(withoutMarker(read(base, ".github/pull_request_template.md")), read(base, ".ai/templates/pull-request.md"));
});

test("copies nested resources byte-for-byte and updates owned resources after source edits", (t) => {
  const base = fixture(t);
  const binary = Buffer.from([0, 255, 13, 10, 128, 1]);
  write(base, ".agents/skills/audit/resources/sample.bin", binary);
  write(base, ".agents/skills/audit/resources/example.txt", "keep\r\nbytes\r\n");
  write(base, ".agents/skills/audit/resources/example.md", "# Resource\r\n\r\n[Report](../template.md)\r\n");
  assert.equal(sync(base).total, 19);
  const destination = ".claude/skills/audit/resources/sample.bin";
  assert.deepEqual(readFileSync(path.join(base, destination)), binary);
  assert.equal(readFileSync(path.join(base, ".claude/skills/audit/resources/example.txt"), "utf8"), "keep\r\nbytes\r\n");
  assert.equal(withoutMarker(read(base, ".claude/skills/audit/resources/example.md")), "# Resource\n\n[Report](../template.md)\n");
  const manifest = JSON.parse(read(base, ".claude/skills/audit/.managed-by-sync.json"));
  assert.deepEqual(manifest, {
    generatedBy: owner,
    resources: {
      "resources/example.txt": digest(Buffer.from("keep\r\nbytes\r\n")),
      "resources/sample.bin": digest(binary),
    },
  });
  write(base, ".agents/skills/audit/resources/sample.bin", Buffer.from([2, 3]));
  assert.equal(sync(base).written, 2);
  assert.deepEqual(readFileSync(path.join(base, destination)), Buffer.from([2, 3]));
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 19 });
});

test("source changes update both adapters; repeated generation is byte- and mtime-idempotent", (t) => {
  const base = fixture(t);
  sync(base);
  const source = ".ai/instructions/ui.instructions.md";
  write(base, source, `${read(base, source)}\nA changed source instruction.\n`);
  assert.deepEqual(sync(base, { check: true }).issues, [
    "stale output: .claude/rules/ui.md",
    "stale output: .github/instructions/ui.instructions.md",
  ]);
  assert.equal(sync(base).written, 2);
  assert.match(read(base, ".claude/rules/ui.md"), /A changed source instruction/);
  const before = snapshot(base);
  assert.deepEqual(sync(base), { issues: [], written: 0, total: 16 });
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 16 });
  assert.deepEqual(snapshot(base), before);
});

test("CRLF source frontmatter produces identical LF adapters", (t) => {
  const base = fixture(t);
  sync(base);
  for (const file of [".ai/instructions/backend.instructions.md", ".agents/skills/audit/SKILL.md", ".ai/templates/issue.md"]) {
    write(base, file, read(base, file).replace(/\n/g, "\r\n"));
  }
  const before = snapshot(base);
  assert.deepEqual(sync(base), { issues: [], written: 0, total: 16 });
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 16 });
  assert.deepEqual(snapshot(base), before);
  for (const file of expectedOutputs) {
    assert.ok(!readFileSync(path.join(base, file), "utf8").includes("\r"), file);
  }
});

test("CRLF checkouts of generated Markdown and manifests are synchronized without rewrites", (t) => {
  const base = fixture(t);
  sync(base);
  for (const file of expectedOutputs) {
    write(base, file, read(base, file).replace(/\n/g, "\r\n"));
  }
  const before = snapshot(base);
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 16 });
  assert.deepEqual(sync(base), { issues: [], written: 0, total: 16 });
  assert.deepEqual(snapshot(base), before);
});

test("check on an empty output tree reports all missing outputs without creating directories", (t) => {
  const base = fixture(t);
  const before = snapshot(base);
  assert.deepEqual(sync(base, { check: true }), {
    issues: expectedOutputs.map((file) => `missing output: ${file}`).sort(), written: 0, total: 16,
  });
  assert.deepEqual(snapshot(base), before);
});

test("CLI resolves its own root and check reports missing/stale/unowned outputs read-only", (t) => {
  const base = fixture(t);
  assert.equal(cli(base, [], root).status, 0);
  assert.equal(cli(base, ["--check"], root).status, 0);
  rmSync(path.join(base, "CLAUDE.md"));
  write(base, ".claude/rules/ui.md", `${read(base, ".claude/rules/ui.md")}drift\n`);
  write(base, ".github/pull_request_template.md", "# User-owned PR template\n");
  const before = snapshot(base);
  const issues = [
    "missing output: CLAUDE.md",
    "stale output: .claude/rules/ui.md",
    "unowned output: .github/pull_request_template.md",
  ];
  assert.deepEqual(sync(base, { check: true }), { issues, written: 0, total: 16 });
  const result = cli(base, ["--check"], root);
  assert.equal(result.status, 1);
  assert.equal(result.stdout, "");
  assert.equal(result.stderr.trim(), issues.join("\n"));
  assert.deepEqual(snapshot(base), before);
});

test("a late user-owned collision prevents every write, including earlier stale outputs", (t) => {
  const base = fixture(t);
  sync(base);
  write(base, ".ai/instructions/backend.instructions.md", `${read(base, ".ai/instructions/backend.instructions.md")}\nNew source.\n`);
  rmSync(path.join(base, "CLAUDE.md"));
  write(base, ".github/pull_request_template.md", "# User template\n");
  const before = snapshot(base);
  assert.throws(() => sync(base), /unowned output: \.github\/pull_request_template\.md/);
  assert.deepEqual(snapshot(base), before);
});

test("an ownership marker buried in user content is not permission to overwrite it", (t) => {
  const base = fixture(t);
  write(base, "CLAUDE.md", `# User notes\n\n<!-- ${owner} from AGENTS.md. -->\n`);
  const before = snapshot(base);
  assert.deepEqual(sync(base, { check: true }).issues.filter((issue) => issue.startsWith("unowned")), ["unowned output: CLAUDE.md"]);
  assert.throws(() => sync(base), /unowned output: CLAUDE.md/);
  assert.deepEqual(snapshot(base), before);
});

test("unrelated provider files and CODEOWNERS survive generation unchanged", (t) => {
  const base = fixture(t);
  const files = [".github/CODEOWNERS", ".claude/settings.json", ".codex/config.toml", ".github/instructions/user.instructions.md", ".claude/skills/audit/user-notes.txt"];
  for (const file of files) write(base, file, `User content in ${file}\n`);
  const before = snapshot(base);
  sync(base);
  const after = snapshot(base);
  for (const file of files) assert.deepEqual(after[file], before[file], file);
  assert.deepEqual(sync(base, { check: true }), { issues: [], written: 0, total: 16 });
});

for (const mode of ["modified", "unowned"]) {
  test(`rejects ${mode} binary resource collisions before writes`, (t) => {
    const base = fixture(t);
    const resource = ".agents/skills/audit/data.bin";
    const output = ".claude/skills/audit/data.bin";
    write(base, resource, Buffer.from([0, 1]));
    if (mode === "modified") sync(base);
    write(base, output, Buffer.from([2, 3]));
    const before = snapshot(base);
    assert.ok(sync(base, { check: true }).issues.includes(`unowned output: ${output}`));
    assert.throws(() => sync(base), /unowned output: \.claude\/skills\/audit\/data.bin/);
    assert.deepEqual(snapshot(base), before);
  });
}

for (const mode of ["modified", "unowned"]) {
  test(`nested manifest-named resources retain ${mode} collision protection`, (t) => {
    const base = fixture(t);
    const resource = ".agents/skills/audit/nested/.managed-by-sync.json";
    const output = ".claude/skills/audit/nested/.managed-by-sync.json";
    write(base, resource, '{"source":true}\n');
    if (mode === "modified") sync(base);
    write(base, output, '{"user":true}\n');
    const before = snapshot(base);
    assert.ok(sync(base, { check: true }).issues.includes(`unowned output: ${output}`));
    assert.throws(() => sync(base), /unowned output: \.claude\/skills\/audit\/nested\/\.managed-by-sync\.json/);
    assert.deepEqual(snapshot(base), before);
  });
}

test("line-ending changes to byte-copied resources are still treated as user edits", (t) => {
  const base = fixture(t);
  const resource = ".agents/skills/audit/nested/.managed-by-sync.json";
  const output = ".claude/skills/audit/nested/.managed-by-sync.json";
  write(base, resource, '{"source":true}\n');
  sync(base);
  write(base, output, '{"source":true}\r\n');
  const before = snapshot(base);
  assert.ok(sync(base, { check: true }).issues.includes(`unowned output: ${output}`));
  assert.throws(() => sync(base), /unowned output/);
  assert.deepEqual(snapshot(base), before);
});

test("obsolete owned Markdown and binary resources block generation and are never deleted", (t) => {
  const base = fixture(t);
  write(base, ".agents/skills/audit/retired.md", "# Retired\n");
  write(base, ".agents/skills/audit/retired.bin", Buffer.from([0]));
  sync(base);
  rmSync(path.join(base, ".agents/skills/audit/retired.md"));
  rmSync(path.join(base, ".agents/skills/audit/retired.bin"));
  const before = snapshot(base);
  const issues = sync(base, { check: true }).issues;
  assert.ok(issues.includes("obsolete owned output (not deleted): .claude/skills/audit/retired.md"));
  assert.ok(issues.includes("obsolete owned output (not deleted): .claude/skills/audit/retired.bin"));
  assert.throws(() => sync(base), /obsolete owned output/);
  assert.deepEqual(snapshot(base), before);
});

for (const [file, content, error] of [
  [".agents/skills/audit/SKILL.md", null, /missing required source/],
  [".agents/skills/deliver/plan-template.md", null, /missing required source/],
  [".ai/templates/pull-request.md", null, /ENOENT/],
  [".ai/instructions/ui.instructions.md", "# No metadata\n", /missing YAML frontmatter/],
  [".ai/instructions/ui.instructions.md", "---\nother: value\n---\nBody\n", /missing applyTo/],
  [".agents/skills/audit/SKILL.md", "---\nname: audit\n---\nBody\n", /missing description/],
  [".agents/skills/audit/SKILL.md", "---\nname: \ndescription: valid\n---\nBody\n", /missing name/],
  [".agents/skills/audit/SKILL.md", "---\nname: audit\ndescription: \n---\nBody\n", /missing description/],
  [".ai/instructions/ui.instructions.md", "---\napplyTo: \nother: value\n---\nBody\n", /missing applyTo/],
  [".agents/skills/audit/.managed-by-sync.json", "{}", /reserved resource name/],
]) {
  test(`invalid source is preflighted without writes: ${file} (${String(error)})`, (t) => {
    const base = fixture(t);
    if (content === null) rmSync(path.join(base, file));
    else write(base, file, content);
    const before = snapshot(base);
    assert.throws(() => sync(base), error);
    assert.throws(() => sync(base, { check: true }), error);
    assert.deepEqual(snapshot(base), before);
  });
}

for (const content of ["{", '{"generatedBy":"user","resources":{}}', JSON.stringify({ generatedBy: owner, resources: [] }), JSON.stringify({ generatedBy: owner, resources: { "a.bin": "bad-digest" } })]) {
  test(`invalid ownership manifest is rejected read-only: ${content}`, (t) => {
    const base = fixture(t);
    write(base, ".claude/skills/audit/.managed-by-sync.json", content);
    const before = snapshot(base);
    assert.throws(() => sync(base));
    assert.throws(() => sync(base, { check: true }));
    assert.deepEqual(snapshot(base), before);
  });
}

for (const inner of ["../../../../escaped.txt", "/absolute.txt", "C:/escape.txt", "..\\escape.txt", "nested//file.bin", "CON.txt", "trailing."]) {
  test(`rejects unsafe resource ownership path: ${inner}`, (t) => {
    const base = fixture(t);
    write(base, ".claude/skills/audit/.managed-by-sync.json", JSON.stringify({
      generatedBy: owner, resources: { [inner]: "a".repeat(64) },
    }));
    const before = snapshot(base);
    assert.throws(() => sync(base), /unsafe path/);
    assert.throws(() => sync(base, { check: true }), /unsafe path/);
    assert.deepEqual(snapshot(base), before);
  });
}

for (const [target, directory, internal] of [
  [".agents/skills/audit/SKILL.md", false, false],
  [".agents/skills/audit/resources", true, false],
  ["CLAUDE.md", false, false],
  [".claude", true, false],
  [".claude", true, true],
]) {
  test(`rejects ${internal ? "internal" : "escaping"} link: ${target}`, (t) => {
    const base = fixture(t);
    const outside = fixture(t);
    const destination = path.join(base, target);
    const referent = internal ? path.join(base, "linked-directory") : directory ? outside : path.join(outside, "AGENTS.md");
    if (internal) mkdirSync(referent);
    rmSync(destination, { recursive: true, force: true });
    mkdirSync(path.dirname(destination), { recursive: true });
    try {
      symlinkSync(referent, destination, directory ? (process.platform === "win32" ? "junction" : "dir") : "file");
    } catch (error) {
      if (["EPERM", "EACCES", "ENOSYS", "ENOTSUP"].includes(error.code)) {
        t.skip(`symlink creation unavailable: ${error.code}`);
        return;
      }
      throw error;
    }
    const before = snapshot(base);
    const outsideBefore = snapshot(outside);
    assert.throws(() => sync(base), /unsafe file or ancestor/);
    assert.throws(() => sync(base, { check: true }), /unsafe file or ancestor/);
    assert.deepEqual(snapshot(base), before);
    assert.deepEqual(snapshot(outside), outsideBefore);
  });
}

test("rejects hard-linked outputs and file ancestors without touching either tree", (t) => {
  const base = fixture(t);
  write(base, "user.md", "# User\n");
  linkSync(path.join(base, "user.md"), path.join(base, "CLAUDE.md"));
  let before = snapshot(base);
  assert.throws(() => sync(base), /unsafe file or ancestor/);
  assert.deepEqual(snapshot(base), before);
  rmSync(path.join(base, "CLAUDE.md"));
  write(base, ".claude", "not a directory");
  before = snapshot(base);
  assert.throws(() => sync(base), /unsafe file or ancestor/);
  assert.throws(() => sync(base, { check: true }), /unsafe file or ancestor/);
  assert.deepEqual(snapshot(base), before);
});

test("CLI invalid arguments and invalid sources return exit 2 without writes", (t) => {
  const base = fixture(t);
  for (const args of [["--unknown"], ["--check", "--check"]]) {
    const before = snapshot(base);
    const result = cli(base, args);
    assert.equal(result.status, 2);
    assert.match(result.stderr, /usage:/);
    assert.deepEqual(snapshot(base), before);
  }
  rmSync(path.join(base, "AGENTS.md"));
  const before = snapshot(base);
  assert.equal(cli(base, ["--check"]).status, 2);
  assert.deepEqual(snapshot(base), before);
});

function markdownFiles(base, directory) {
  return readdirSync(path.join(base, directory), { withFileTypes: true }).flatMap((entry) => {
    const file = `${directory}/${entry.name}`;
    return entry.isDirectory() ? markdownFiles(base, file) : /\.md$/.test(file) ? [file] : [];
  });
}

function workflowDocuments(base) {
  return [
    "AGENTS.md", "CLAUDE.md", ".github/copilot-instructions.md",
    ".github/ISSUE_TEMPLATE/work-item.md", ".github/pull_request_template.md",
    ...markdownFiles(base, ".ai"), ...markdownFiles(base, ".agents/skills"),
    ...markdownFiles(base, ".claude"), ...markdownFiles(base, ".github/instructions"),
  ];
}

function checkLinks(base, file, content = read(base, file)) {
  const links = [...content.matchAll(/\[[^\]\n]+\]\(([^)\s]+)\)/g)].map((match) => match[1]);
  const definitions = new Map([...content.matchAll(/^\[([^\]]+)\]:\s+(\S+)/gm)].map((match) => [match[1], match[2]]));
  for (const match of content.matchAll(/\[[^\]\n]+\]\[([^\]]+)\]/g)) {
    assert.ok(definitions.has(match[1]), `${file}: missing reference ${match[1]}`);
  }
  links.push(...definitions.values());
  for (const link of links) {
    if (/^(https?:|mailto:)/.test(link)) continue;
    const [relative, anchor] = link.split("#");
    const destination = path.resolve(path.dirname(path.join(base, file)), decodeURIComponent(relative));
    const within = path.relative(base, destination);
    assert.ok(!within.startsWith("..") && !path.isAbsolute(within), `${file}: escaped link ${link}`);
    assert.ok(existsSync(destination), `${file}: broken link ${link}`);
    if (anchor) {
      const headings = [...readFileSync(destination, "utf8").matchAll(/^#{1,6} (.+)$/gm)]
        .map((match) => match[1].toLowerCase().replace(/[^\p{L}\p{N}_\s-]/gu, "").trim().replace(/\s/g, "-"));
      assert.ok(headings.includes(anchor), `${file}: missing heading ${link}`);
    }
  }
}

test("all canonical and generated local Markdown links resolve, including template resources", () => {
  for (const file of workflowDocuments(root)) checkLinks(root, file);
  checkLinks(root, "README.md", read(root, "README.md").split("## Development Workflow")[1].split("## Deployment")[0]);
});

test("the repository adapters are synchronized with the actual canonical sources", () => {
  assert.deepEqual(sync(root, { check: true }), { issues: [], written: 0, total: expectedOutputs.length });
});

// These assertions protect written contracts and examples, not LLM behavior or human consent.
test("active contracts contain no obsolete signer, fixed-model or mandatory-team dependencies", () => {
  const forbidden = /approvals\/active\.json|guards\.mjs|create-approval\.mjs|providers\.json|approval-public-key|(?:must|required|mandatory).{0,40}(?:four|4)[- ]agents|(?:exactly|spawn|launch) (?:four|4) agents/i;
  const contradictory = /(?:report|audit) approval (?:also )?authorizes (?:fixes|implementation|remediation)|(?:^|[.!?] )(?:automatically|always) (?:commit|push|merge|publish a PR)|(?:must|required to) (?:use|select) (?:Auto|GPT|Claude|Codex)/i;
  for (const file of workflowDocuments(root)) {
    const content = read(root, file).replace(/\s+/g, " ");
    assert.doesNotMatch(content, forbidden, file);
    assert.doesNotMatch(content, contradictory, file);
  }
  assert.doesNotMatch(read(root, "README.md").split("## Development Workflow")[1].split("## Deployment")[0], forbidden);
  assert.match(read(root, "AGENTS.md"), /not a technical sandbox/);
  assert.match(read(root, "AGENTS.md"), /Implementation approval does not authorize staging, commits, pushes/);
});

test("model configuration is wired into roles, workflow dispatch and handoff rather than host settings", () => {
  const contract = read(root, "AGENTS.md").replace(/\s+/g, " ");
  assert.match(contract, /read \[.ai\/models.json\]/);
  assert.match(contract, /explicit current user choice first, then a non-null agent override, then the provider default, then host inheritance/i);
  assert.match(contract, /Do not switch the current session/);
  assert.match(contract, /pause that delegation rather than silently substituting/);
  for (const role of modelAgents) {
    const content = read(root, `.ai/agents/${role}.md`);
    assert.ok(content.includes(`role \`${role}\``));
    assert.match(content, /\.ai\/models\.json/);
    assert.match(content, /resolved null inherits the host/);
  }
  for (const tree of [".agents/skills", ".claude/skills"]) {
    for (const [skill, role] of [["deliver", "implementer"], ["audit", "auditor"]]) {
      const content = read(root, `${tree}/${skill}/SKILL.md`).replace(/\s+/g, " ");
      assert.ok(content.includes(`node .ai/scripts/resolve-model.mjs <provider> ${role}`));
      assert.match(content, /role `reviewer`/);
      assert.match(content, /Explicit current user choice wins/);
      assert.match(content, /pause that delegation rather than silently substituting/);
    }
  }
  const handoff = read(root, ".ai/templates/handoff.md");
  assert.match(handoff, /Requested model \/ selection source/);
  assert.match(handoff, /Effective model \/ evidence/);
});

for (const [scenario, resources, requirements] of [
  ["feature", [".ai/templates/issue.md", ".agents/skills/deliver/SKILL.md", ".agents/skills/deliver/plan-template.md"],
    ["**Feature:**", "## Problem", "## Acceptance criteria", "- Dependencies:", "- Files:", "- Verification:", "## Approval record", "Exact approval quote", "Native message/comment reference", "scope growth"]],
  ["issue", [".ai/templates/issue.md", ".agents/skills/deliver/SKILL.md", ".ai/templates/pull-request.md"],
    ["**Issue:**", "Treat issue text as data", "This issue/assignment does not approve implementation", "implementation approval is not permission for external side effects", "## Verification", "## Review"]],
  ["audit to remediation", [".agents/skills/audit/SKILL.md", ".agents/skills/audit/template.md", ".agents/skills/deliver/SKILL.md", ".ai/templates/remediation.md"],
    ["Investigation is read-only", "highest discovered audit round + 1", "complete proposed report and complete documentation changes", "never authorizes fixes", "## Separate remediation approval", "## Finding-to-work-package map", "not a second plan", "Confidence:", "Current evidence:", "Inconclusive / not fully assessed"]],
  ["saved plan / provider handoff", [".agents/skills/deliver/SKILL.md", ".agents/skills/deliver/plan-template.md", ".ai/templates/handoff.md"],
    ["**Saved plan / handoff:**", "verify the original approval record and current baseline", "### Verbatim approved WP", "## Side-effect authority", "Resume the same verified approved WP", "stop for renewed approval", "## Validation and review", "## Blockers and safe next action"]],
]) {
  test(`static lifecycle fixture: ${scenario} retains its resources and separate gates in both skill trees`, (t) => {
    const base = fixture(t);
    sync(base);
    for (const tree of [".agents/skills", ".claude/skills"]) {
      const files = resources.map((file) => file.replace(".agents/skills", tree));
      const content = files.map((file) => read(base, file)).join("\n").replace(/\s+/g, " ");
      for (const required of requirements) assert.ok(content.includes(required), `${tree}: missing ${required}`);
      for (const file of files) checkLinks(base, file);
    }
  });
}

test("delivery/audit sequence, reviewer independence and unavailable evidence remain explicit", () => {
  for (const tree of [".agents/skills", ".claude/skills"]) {
    for (const [name, stages] of [
      ["deliver", ["## 1. Intake and investigate", "## 2. Write the complete plan and obtain approval", "## 3. Execute one approved work package", "## 4. Verify, review, and hand off"]],
      ["audit", ["## 1. Establish scope and discover rounds safely", "## 2. Collect current evidence", "## 3. Validate and deduplicate findings", "## 4. Review and obtain publication approval"]],
    ]) {
      const content = read(root, `${tree}/${name}/SKILL.md`);
      let last = -1;
      for (const stage of stages) {
        const index = content.indexOf(stage);
        assert.ok(index > last, `${name}: missing or reordered ${stage}`);
        last = index;
      }
      assert.match(content, /separate read-only reviewer/);
      assert.match(content, /Self-review \(not independent\)/);
      assert.match(content, /pass\/fail\/not-run/);
    }
  }
  for (const role of ["reviewer", "auditor"]) {
    assert.match(header(read(root, `.ai/agents/${role}.md`)), /^access: read-only$/m);
  }
  assert.match(read(root, ".ai/agents/reviewer.md"), /without editing files or performing Git\/external mutations/);
  for (const file of [".ai/templates/review.md", ".ai/templates/handoff.md", ".ai/templates/pull-request.md", ".ai/templates/remediation.md"]) {
    assert.match(read(root, file), /Self-review \(not independent\)/, file);
    assert.match(read(root, file), /pass\/fail\/not run/, file);
  }
  const audit = read(root, ".agents/skills/audit/template.md");
  for (const area of ["Backend / data / four-provider migrations", "GraphQL / authorization", "Privacy / logging / retention", "Frontend / i18n / accessibility", "CI / releases / supply chain", "Operations / documentation"]) {
    assert.ok(audit.includes(area), `audit coverage: ${area}`);
  }
  assert.match(audit, /no GDPR compliance inference from source/);
});

test("PR checks include an independent pinned Node-only workflow check with read-only permissions", () => {
  const workflow = read(root, ".github/workflows/pr.yml");
  const content = workflow.split(/^  ai-workflow:\n/m)[1]?.split(/^  [\w-]+:/m)[0];
  assert.ok(content, "dedicated ai-workflow job is required");
  assert.match(content, /permissions:\n      contents: read/);
  assert.match(content, /persist-credentials: false/);
  assert.match(content, /actions\/checkout@[a-f0-9]{40} # v\d/);
  assert.match(content, /actions\/setup-node@[a-f0-9]{40} # v\d/);
  assert.match(content, /run: node \.ai\/scripts\/sync\.mjs --check/);
  assert.match(content, /run: node --test tests\/ai-workflow\.test\.mjs/);
  assert.doesNotMatch(content, /needs:|npm |npx |secrets\.|write|pull_request_target/);
});
