#!/usr/bin/env node
// Provider-neutral tool-use guard. One script serves GitHub Copilot, Claude Code and Codex.
// Usage: node .ai/hooks/guards.mjs <pre|post> [--provider=copilot|claude|codex]
// The provider only changes how events are read (tool names, argument shapes) and how a decision
// is reported; the rules are identical. Hook configs are generated by .ai/scripts/sync.mjs.
// Security-sensitive: fail closed. Any error while evaluating a PreToolUse event denies the call.
import { execFileSync } from "node:child_process";
import { createHash, verify as verifySignature } from "node:crypto";
import { existsSync, readFileSync, realpathSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const repositoryRealRoot = realpathSync(repositoryRoot);
const providerFlag = process.argv.find((argument) => argument.startsWith("--provider="))?.split("=")[1];
// Without the flag, the provider is inferred from the event shape once the event is read.
let provider = providerFlag ?? "copilot";
const heavyFileLimit = 20 * 1024;
const forcedReadLimit = 60 * 1024;
const approvalMaxAgeMs = Number(process.env.AI_APPROVAL_MAX_AGE_MS ?? 2 * 60 * 60 * 1000);
const approvalPublicKeyFile = process.env.AI_APPROVAL_PUBLIC_KEY_FILE
  ? path.resolve(repositoryRoot, process.env.AI_APPROVAL_PUBLIC_KEY_FILE)
  : path.resolve(repositoryRoot, ".ai/approval-public-key.pem");
const approvalFile = process.env.AI_APPROVAL_FILE
  ? path.resolve(repositoryRoot, process.env.AI_APPROVAL_FILE)
  : path.resolve(repositoryRoot, ".ai/approvals/active.json");

function isRecord(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function errorMessage(error) {
  return error instanceof Error ? error.message : String(error);
}

async function readEvent() {
  let input = "";
  for await (const chunk of process.stdin) {
    input += chunk.toString();
  }
  return JSON.parse(input);
}

function normalizeArguments(value) {
  if (isRecord(value)) {
    return value;
  }
  if (typeof value !== "string") {
    return value === undefined ? {} : { raw: value };
  }
  try {
    const parsed = JSON.parse(value);
    return isRecord(parsed) ? parsed : { raw: parsed };
  } catch {
    return { raw: value, command: value, patch: value };
  }
}

function getToolName(event) {
  return String(event.toolName ?? event.tool_name ?? "");
}

function getToolArguments(event) {
  return normalizeArguments(event.toolArgs ?? event.tool_input);
}

function getArgumentPath(args) {
  for (const key of ["path", "filePath", "file_path", "targetPath", "target_file", "notebook_path"]) {
    if (typeof args[key] === "string" && args[key].length > 0) {
      return args[key];
    }
  }
  return typeof args.raw === "string" ? args.raw : "";
}

function getExplicitPath(args) {
  for (const key of ["path", "filePath", "file_path", "targetPath", "target_file", "notebook_path"]) {
    if (typeof args[key] === "string" && args[key].length > 0) {
      return args[key];
    }
  }
  return "";
}

function resolveArgumentPath(event, args) {
  const filePath = getArgumentPath(args);
  if (!filePath) {
    return "";
  }
  const base = typeof event.cwd === "string" ? event.cwd : repositoryRoot;
  return path.resolve(base, filePath);
}

function getFileSize(filePath) {
  if (!filePath) {
    return null;
  }
  try {
    const stats = statSync(filePath);
    return stats.isFile() ? stats.size : null;
  } catch {
    return null;
  }
}

function normalizedPath(filePath) {
  return filePath.replace(/\\/g, "/");
}

function isHeavyFile(filePath) {
  const normalized = normalizedPath(filePath);
  return /(?:^|\/)package-lock\.json$/i.test(normalized)
    || /(?:^|\/)packages\.lock\.json$/i.test(normalized)
    || /(?:^|\/)graphql\/generated\.ts$/i.test(normalized)
    || /(?:^|\/)docs\/AUDIT[^/]*\.md$/i.test(normalized)
    || /(?:^|\/)public\/i18n\/[^/]+\.json$/i.test(normalized);
}

// AI-control files the agent must not rewrite on its own: instructions, hooks, agent/skill
// definitions, per-host settings, and CODEOWNERS. Set AI_ALLOW_GUARD_EDITS=1 for a deliberate change.
function isProtectedPath(filePath) {
  const normalized = normalizedPath(filePath).replace(/^(?:\.\/)+/, "");
  return /(?:^|\/)\.(?:ai|agents|claude|codex|cursor)\//i.test(normalized)
    || /(?:^|\/)\.github\/(?:hooks|copilot|agents|skills|instructions)\//i.test(normalized)
    || /(?:^|\/)\.github\/(?:copilot-instructions\.md|CODEOWNERS)$/i.test(normalized)
    || /(?:^|\/)(?:AGENTS(?:\.override)?|CLAUDE|GEMINI)\.md$/i.test(normalized)
    || /^CODEOWNERS$/i.test(normalized);
}

function guardEditsAllowed() {
  return (process.env.AI_ALLOW_GUARD_EDITS ?? process.env.COPILOT_ALLOW_GUARD_EDITS) === "1";
}

function gitWriteAllowed() {
  return (process.env.AI_ALLOW_GIT_WRITE ?? process.env.COPILOT_ALLOW_GIT_WRITE) === "1";
}

function canonicalize(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalize).join(",")}]`;
  if (isRecord(value)) {
    return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalize(value[key])}`).join(",")}}`;
  }
  return JSON.stringify(value);
}

function approvalHash(approval) {
  const copy = { ...approval };
  delete copy.approvalHash;
  delete copy.approvalSignature;
  return createHash("sha256").update(canonicalize(copy)).digest("hex");
}

function normalizeApprovedPath(filePath) {
  const normalized = normalizedPath(filePath).replace(/^(?:\.\/)+/, "");
  if (!normalized || normalized.startsWith("../") || normalized === "..") return "";
  const resolved = path.resolve(repositoryRoot, normalized);
  const relative = path.relative(repositoryRoot, resolved).replace(/\\/g, "/");
  if (!relative || relative.startsWith("../") || path.isAbsolute(relative)) return "";
  return relative;
}

function loadApproval() {
  if (!existsSync(approvalFile)) {
    return { valid: false, reason: `Approval artifact is missing: ${path.relative(repositoryRoot, approvalFile).replace(/\\/g, "/")}` };
  }
  let approval;
  try {
    approval = JSON.parse(readFileSync(approvalFile, "utf8"));
  } catch (error) {
    return { valid: false, reason: `Approval artifact is not valid JSON: ${errorMessage(error)}` };
  }
  const required = ["planId", "workPackageId", "approvedFiles", "approvalHash", "approvalSignature", "approvedBy", "approvedAt"];
  if (!required.every((key) => approval[key] !== undefined)) {
    return { valid: false, reason: `Approval artifact is missing one or more required fields: ${required.join(", ")}` };
  }
  if (![approval.planId, approval.workPackageId, approval.approvedBy].every((value) => typeof value === "string" && value.trim().length > 0)) {
    return { valid: false, reason: "Approval artifact planId, workPackageId, and approvedBy must be non-empty strings." };
  }
  if (!Array.isArray(approval.approvedFiles) || approval.approvedFiles.length === 0
    || approval.approvedFiles.some((file) => typeof file !== "string" || !normalizeApprovedPath(file))) {
    return { valid: false, reason: "Approval artifact approvedFiles must be a non-empty list of repository-relative files." };
  }
  const approvedAt = Date.parse(approval.approvedAt);
  if (!Number.isFinite(approvedAt)) {
    return { valid: false, reason: "Approval artifact approvedAt must be an ISO-8601 timestamp." };
  }
  if (!Number.isFinite(approvalMaxAgeMs) || approvalMaxAgeMs <= 0 || Date.now() - approvedAt > approvalMaxAgeMs) {
    return { valid: false, reason: "Approval artifact has expired." };
  }
  if (approvedAt - Date.now() > 60 * 1000) {
    return { valid: false, reason: "Approval artifact approvedAt is too far in the future." };
  }
  if (approvalHash(approval) !== approval.approvalHash) {
    return { valid: false, reason: "Approval artifact approvalHash does not match its contents." };
  }
  if (!existsSync(approvalPublicKeyFile)) {
    return { valid: false, reason: `Approval verification key is missing: ${path.relative(repositoryRoot, approvalPublicKeyFile).replace(/\\/g, "/")}. Provision the host-side approval public key before implementation.` };
  }
  let publicKey;
  try {
    publicKey = readFileSync(approvalPublicKeyFile, "utf8");
    const signature = Buffer.from(approval.approvalSignature, "base64url");
    const unsigned = { ...approval };
    delete unsigned.approvalSignature;
    const verified = verifySignature(null, Buffer.from(canonicalize(unsigned)), publicKey, signature);
    if (!verified) {
      return { valid: false, reason: "Approval artifact approvalSignature is invalid." };
    }
  } catch (error) {
    return { valid: false, reason: `Approval artifact signature verification failed: ${errorMessage(error)}` };
  }
  const files = [...new Set(approval.approvedFiles.map(normalizeApprovedPath))].sort();
  return { valid: true, approval, files };
}

function approvedScopeForWrite(event, args, targets) {
  const loaded = loadApproval();
  if (!loaded.valid) return { valid: false, reason: loaded.reason };
  const requestedPlan = args.planId ?? args.plan_id ?? event.planId ?? event.plan_id;
  const requestedWp = args.workPackageId ?? args.work_package_id ?? event.workPackageId ?? event.work_package_id;
  if (requestedPlan && String(requestedPlan) !== String(loaded.approval.planId)) {
    return { valid: false, reason: `Write planId ${requestedPlan} does not match approved plan ${loaded.approval.planId}.` };
  }
  if (requestedWp && String(requestedWp) !== String(loaded.approval.workPackageId)) {
    return { valid: false, reason: `Write workPackageId ${requestedWp} does not match approved work package ${loaded.approval.workPackageId}.` };
  }
  const allowed = new Set(loaded.files);
  const outOfScope = [];
  for (const target of targets) {
    const relative = path.relative(repositoryRoot, target).replace(/\\/g, "/");
    if (!relative || relative.startsWith("../") || path.isAbsolute(relative) || !allowed.has(relative)) {
      outOfScope.push(relative || target);
      continue;
    }
    if (existsSync(target)) {
      let realTarget;
      try {
        realTarget = realpathSync(target);
      } catch {
        outOfScope.push(relative);
        continue;
      }
      const realRelative = path.relative(repositoryRealRoot, realTarget);
      if (realRelative.startsWith("../") || path.isAbsolute(realRelative)) {
        outOfScope.push(`${relative} (symlink escapes repository)`);
      }
    }
  }
  if (outOfScope.length > 0) {
    return { valid: false, reason: `Write target(s) outside the approved work-package scope: ${outOfScope.join(", ")}` };
  }
  return { valid: true, approval: loaded.approval };
}

// Tool names are compared lower-cased, so Claude's Edit/Write/MultiEdit/Bash/Read, Copilot's
// edit/create/bash/view and Codex's apply_patch/shell all land in the same classes.
const writeTools = new Set([
  "edit", "create", "write", "str_replace", "str_replace_editor", "create_file", "apply_patch",
  "multiedit", "notebookedit",
]);
const shellTools = new Set(["bash", "powershell", "shell", "local_shell"]);
const readTools = new Set(["view", "read"]);
const pullRequestTool = /(?:^|__)(?:create|update)_pull_request$/;

function patchText(args) {
  return [args.patch, args.input, args.raw].find((value) => typeof value === "string");
}

function writeTargets(event, args) {
  const targets = [];
  const explicit = getExplicitPath(args);
  if (explicit) {
    targets.push(explicit);
  }
  targets.push(...localePathsFromPatch(patchText(args)));
  // Some hosts (Codex) deliver apply_patch through the shell; read its file headers too.
  targets.push(...localePathsFromPatch(shellCommandText(args)));
  const base = typeof event.cwd === "string" ? event.cwd : repositoryRoot;
  return targets.map((target) => path.resolve(base, target));
}

function currentBranch() {
  try {
    return execFileSync("git", ["symbolic-ref", "--short", "HEAD"], {
      cwd: repositoryRoot,
      encoding: "utf8",
      timeout: 3000,
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return "";
  }
}

function hasViewRange(args) {
  const range = args.view_range ?? args.viewRange ?? args.range;
  if (Array.isArray(range)) {
    return range.length >= 2;
  }
  if (typeof range === "string") {
    return range.trim().length > 0;
  }
  return ["startLine", "endLine", "start_line", "end_line", "offset", "limit"]
    .some((key) => args[key] !== undefined && args[key] !== null);
}

// Single-quoted (or escaped) "$" is literal, so the tokenizer swaps it for a private-use marker.
// Callers test for expansion on the marked text, then restore it with restoreLiteral().
const literalDollar = "\uE000";

function restoreLiteral(value) {
  return value.replaceAll(literalDollar, "$");
}

function splitShellSegments(command, powershell) {
  const segments = [];
  let tokens = [];
  let token = "";
  let tokenStarted = false;
  let quote = "";

  const pushToken = () => {
    if (tokenStarted) {
      tokens.push(token);
      token = "";
      tokenStarted = false;
    }
  };
  const pushSegment = () => {
    pushToken();
    if (tokens.length > 0) {
      segments.push(tokens);
      tokens = [];
    }
  };

  for (let index = 0; index < command.length; index += 1) {
    const character = command[index];
    const next = command[index + 1];

    if (quote) {
      if (character === quote) {
        if (powershell && quote === "'" && next === "'") {
          token += "'";
          index += 1;
        } else {
          quote = "";
        }
      } else if (quote === '"' && (character === "\\" || (powershell && character === "`")) && next) {
        token += next === "$" ? literalDollar : next;
        index += 1;
      } else if (quote === "'" && character === "$") {
        token += literalDollar;
      } else {
        token += character;
      }
      tokenStarted = true;
      continue;
    }

    if (character === "'" || character === '"') {
      quote = character;
      tokenStarted = true;
    } else if (powershell && character === "`" && next) {
      token += next === "$" ? literalDollar : next;
      tokenStarted = true;
      index += 1;
    } else if (character === "\\" && next && /[\s'"\\]/.test(next)) {
      token += next;
      tokenStarted = true;
      index += 1;
    } else if (character === ";" || character === "|" || character === "&"
      || character === "\n" || character === "\r") {
      pushSegment();
    } else if (/\s/.test(character)) {
      pushToken();
    } else {
      token += character;
      tokenStarted = true;
    }
  }

  pushSegment();
  return segments;
}

function shellCommandText(args) {
  const values = [args.command, args.script, args.cmd, args.shellCommand, args.raw];
  return values
    .filter((value) => typeof value === "string")
    .join("\n");
}

const dynamicTitle = /(?:\$\(|\$\{|(?:^|[^\\])\$[A-Za-z_]|%[A-Za-z_][A-Za-z0-9_]*%|`)/;

function shellPullRequestTitles(command, powershell) {
  const titles = [];
  for (const segment of splitShellSegments(command, powershell)) {
    for (let index = 0; index < segment.length - 2; index += 1) {
      const executable = path.basename(segment[index]).toLowerCase();
      const action = segment[index + 2]?.toLowerCase();
      if ((executable !== "gh" && executable !== "gh.exe")
        || segment[index + 1]?.toLowerCase() !== "pr"
        || !["create", "edit"].includes(action)) {
        continue;
      }

      let hasTitle = false;
      let autoFilled = false;
      for (let option = index + 3; option < segment.length; option += 1) {
        const value = segment[option];
        if (value === "--title" || value === "-t") {
          const title = segment[option + 1];
          hasTitle = true;
          titles.push({
            title: restoreLiteral(title ?? ""),
            dynamic: !title || dynamicTitle.test(title),
          });
          option += 1;
        } else if (value.startsWith("--title=") || value.startsWith("-t=")) {
          const title = value.slice(value.indexOf("=") + 1);
          hasTitle = true;
          titles.push({
            title: restoreLiteral(title),
            dynamic: !title || dynamicTitle.test(title),
          });
        } else if (action === "create" && (value === "-f" || value.startsWith("--fill"))) {
          autoFilled = true;
        }
      }

      // --fill derives the title from commits, so commitlint cannot check a literal.
      if (autoFilled && !hasTitle) {
        titles.push({ title: "", dynamic: true });
      }
    }
  }
  return titles;
}

// Returns [{ sub, args }] for each `git <sub> ...` invocation at the start of a shell segment.
function gitInvocations(command, powershell) {
  const invocations = [];
  const wrappers = /^(?:sudo|env|command|time|exec|nohup|[A-Za-z_][A-Za-z0-9_]*=.*)$/;
  for (const segment of splitShellSegments(command, powershell)) {
    const at = segment.findIndex((token) => ["git", "git.exe"].includes(path.basename(token).toLowerCase()));
    if (at < 0 || !segment.slice(0, at).every((token) => wrappers.test(token))) {
      continue;
    }
    let cursor = at + 1;
    while (cursor < segment.length && segment[cursor].startsWith("-")) {
      cursor += ["-C", "-c", "--git-dir", "--work-tree", "--namespace"].includes(segment[cursor]) ? 2 : 1;
    }
    if (segment[cursor]) {
      invocations.push({ sub: segment[cursor].toLowerCase(), args: segment.slice(cursor + 1) });
    }
  }
  return invocations;
}

const fileReaders = new Set(["cat", "type", "get-content", "gc", "more", "less", "bat", "nl"]);

function shellMutationTargets(event, command, powershell) {
  const base = typeof event.cwd === "string" ? event.cwd : repositoryRoot;
  const targets = [];
  const segments = splitShellSegments(command, powershell);
  const patchTargets = localePathsFromPatch(command);
  const hasPatchCommand = /(?:^|[;&|\n])\s*(?:apply_patch|applypatch)(?:\s|$)/im.test(command);
  if (hasPatchCommand) {
    if (patchTargets.length === 0) {
      targets.push("<unresolved-shell-write>");
    } else {
      targets.push(...patchTargets.map((target) => path.resolve(base, target)));
    }
  }
  const add = (value) => {
    if (typeof value !== "string" || !value || value.startsWith("-")) return;
    targets.push(path.resolve(base, restoreLiteral(value)));
  };
  for (const segment of segments) {
    const executable = path.basename(segment[0] ?? "").toLowerCase();
    if (executable === "git" || executable === "git.exe") {
      for (let index = 1; index < segment.length; index += 1) {
        if (segment[index] === "--output" || segment[index] === "-o") add(segment[index + 1]);
        else if (segment[index].startsWith("--output=")) add(segment[index].slice("--output=".length));
      }
    }
    if (["apply_patch", "applypatch"].includes(executable)) {
      continue;
    }
    if (["tee", "set-content", "add-content", "out-file"].includes(executable)) {
      add(segment[1]);
      continue;
    }
    if (["sed", "perl"].includes(executable) && segment.some((arg) => /(?:^|-)(?:i|in-place)(?:=|$)/.test(arg))) {
      for (const arg of segment.slice(1)) if (!arg.startsWith("-")) add(arg);
      continue;
    }
    if (["cp", "copy", "copy-item", "mv", "move", "move-item"].includes(executable)) {
      const operands = segment.slice(1).filter((arg) => !arg.startsWith("-"));
      if (operands.length > 0) add(operands.at(-1));
      continue;
    }
    if (["rm", "del", "erase", "remove-item"].includes(executable)) {
      for (const arg of segment.slice(1)) add(arg);
      continue;
    }
    if (["dd", "install", "truncate", "touch"].includes(executable)) {
      for (const arg of segment.slice(1)) add(arg);
      continue;
    }
    if (["find", "xargs"].includes(executable) && /(?:-exec(?:dir)?|-delete|\bxargs\b)/i.test(segment.join(" "))) {
      targets.push("<unresolved-shell-write>");
      continue;
    }
    if (["python", "python3", "node", "node.exe", "ruby", "php", "bash", "sh", "pwsh", "powershell", "powershell.exe", "perl", "awk", "gawk"].includes(executable)
      && /(?:>|>>|tee|writefile|writefilesync|appendfile|appendfilesync|unlink|unlinkSync|rmSync|renameSync|copyFileSync|fs\.(?:write|append|rm|rename|copy)|write_text|write_bytes|remove|open\([^)]*['\"](?:w|a))/i.test(segment.join(" "))) {
      // Dynamic interpreter writes cannot be safely mapped to approved files.
      targets.push("<unresolved-shell-write>");
    }
    if (segment.some((token) => /^>>?$/.test(token) || /^>>/.test(token))) {
      const redirectIndex = segment.findIndex((token) => /^>>?$/.test(token) || /^>>/.test(token));
      add(segment[redirectIndex + 1]);
    }
    const compactRedirect = command.match(/(?:^|[;|&\n])\s*[^;|&\n]*?\s*(?:>>?)\s*([^;|&\n]+)/);
    if (compactRedirect?.[1]) add(compactRedirect[1].trim().split(/\s+/)[0]);
  }
  return [...new Set(targets)];
}

// Whole-file reads of heavy files through the shell, unless the output is limited by a pipe.
function shellHeavyReads(event, command, powershell) {
  if (/\|\s*(?:head|tail|select-object|sed|rg|grep|jq|findstr|select-string)\b/i.test(command)) {
    return [];
  }
  const base = typeof event.cwd === "string" ? event.cwd : repositoryRoot;
  const hits = [];
  for (const segment of splitShellSegments(command, powershell)) {
    if (!fileReaders.has(path.basename(segment[0] ?? "").toLowerCase())) {
      continue;
    }
    for (const arg of segment.slice(1)) {
      if (arg.startsWith("-") || !isHeavyFile(arg)) {
        continue;
      }
      const resolved = path.resolve(base, restoreLiteral(arg));
      const size = getFileSize(resolved);
      if (size !== null && size > heavyFileLimit) {
        hits.push({ file: path.basename(resolved), size });
      }
    }
  }
  return hits;
}

let commitlint;
async function getCommitlint() {
  if (commitlint) {
    return commitlint;
  }
  try {
    const [lintModule, loadModule] = await Promise.all([
      import("@commitlint/lint"),
      import("@commitlint/load"),
    ]);
    const lint = lintModule.default ?? lintModule.lint;
    const load = loadModule.default ?? loadModule.load;
    const config = await load({}, { cwd: repositoryRoot });
    commitlint = { lint, config };
    return commitlint;
  } catch (error) {
    process.stderr.write(`[ai guard] commitlint unavailable: ${errorMessage(error)}\n`);
    return null;
  }
}

function configuredValues(config, ruleName) {
  const rule = config.rules?.[ruleName];
  return Array.isArray(rule) && Array.isArray(rule[2]) ? rule[2] : [];
}

async function lintTitle(title) {
  const loaded = await getCommitlint();
  if (!loaded) {
    return { valid: false, unavailable: true };
  }
  const result = await loaded.lint(title, loaded.config.rules, loaded.config);
  const errors = Array.isArray(result.errors)
    ? result.errors.map((error) => `${error.name}: ${error.message}`)
    : [];
  return { valid: result.valid !== false, errors, config: loaded.config };
}

// Copilot reads a JSON decision from stdout. Claude Code and Codex treat exit code 2 with the
// reason on stderr as a block, which is the most conservative contract for a PreToolUse hook.
function deny(reason) {
  if (provider === "copilot") {
    process.stdout.write(`${JSON.stringify({
      permissionDecision: "deny",
      permissionDecisionReason: reason,
    })}\n`);
  } else {
    process.stderr.write(`${reason}\n`);
    process.exitCode = 2;
  }
}

function addContext(text) {
  const payload = provider === "copilot"
    ? { additionalContext: text }
    : { hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: text } };
  process.stdout.write(`${JSON.stringify(payload)}\n`);
}

async function preToolUse(event, toolName, args) {
  const filePath = resolveArgumentPath(event, args);
  const size = getFileSize(filePath);
  const tool = toolName.toLowerCase();
  const isShell = shellTools.has(tool);
  const isRead = readTools.has(tool);
  const forcedRead = args.forceReadLargeFiles === true || args.force_read_large_files === true;

  if (isRead && forcedRead && size !== null && size > forcedReadLimit) {
    deny(`Do not force-read files larger than 60 KB. Use rg or jq, then read focused view_range chunks.`);
    return;
  }

  if (isRead && size !== null && size > heavyFileLimit
    && isHeavyFile(filePath) && !hasViewRange(args)) {
    deny(`Avoid full-reading ${path.basename(filePath)} (${Math.ceil(size / 1024)} KB). Use rg or jq, then read a focused view_range; chunked reads are fine.`);
    return;
  }

  if (writeTools.has(tool)) {
    const targets = writeTargets(event, args);
    // Fail closed: a write whose target cannot be resolved is not assumed to be safe.
    if (targets.length === 0) {
      deny(`Cannot resolve the write target of the "${toolName}" tool call, so it is denied. Retry with an explicit file path argument.`);
      return;
    }
    if (!guardEditsAllowed()) {
      const scope = approvedScopeForWrite(event, args, targets);
      if (!scope.valid) {
        deny(`Implementation write denied: ${scope.reason}`);
        return;
      }
    }
    const protectedTarget = guardEditsAllowed() ? undefined : targets.find(isProtectedPath);
    if (protectedTarget) {
      const display = path.relative(repositoryRoot, protectedTarget).replace(/\\/g, "/");
      deny(`${display} is part of the AI control surface (AGENTS.md, .ai/, .agents/, .claude/, .codex/, hooks, agents, skills, instructions, settings, CODEOWNERS). Ask the user to make or explicitly approve this change; a human can set AI_ALLOW_GUARD_EDITS=1 for a deliberate edit. Generated provider files are changed by editing their source and running \`node .ai/scripts/sync.mjs\`.`);
      return;
    }
  }

  const command = isShell ? shellCommandText(args) : "";

  if (isShell && !guardEditsAllowed()) {
    const mutationTargets = shellMutationTargets(event, command, tool === "powershell");
    if (mutationTargets.some((target) => target === "<unresolved-shell-write>")) {
      deny("Denied shell command: it contains a dynamic or interpreter-based file write whose target cannot be resolved safely. Use an explicit write tool or a simple command with a resolvable target inside the approved work-package scope.");
      return;
    }
    const patched = [...writeTargets(event, args), ...mutationTargets].find(isProtectedPath);
    if (patched) {
      const display = path.relative(repositoryRoot, patched).replace(/\\/g, "/");
      deny(`${display} is part of the AI control surface; a shell-delivered patch may not modify it. Ask the user to make or explicitly approve this change.`);
      return;
    }
    if (mutationTargets.length > 0) {
      const scope = approvedScopeForWrite(event, args, mutationTargets);
      if (!scope.valid) {
        deny(`Shell write denied: ${scope.reason}`);
        return;
      }
    }
  }

  if (isShell) {
    for (const hit of shellHeavyReads(event, command, tool === "powershell")) {
      deny(`Avoid dumping ${hit.file} (${Math.ceil(hit.size / 1024)} KB) through the shell. Use rg or jq, then read a focused range (for example with head, tail, or sed -n).`);
      return;
    }

    if (!gitWriteAllowed()) {
      const onProtectedBranch = ["main", "master"].includes(currentBranch());
      for (const { sub, args: gitArgs } of gitInvocations(command, tool === "powershell")) {
        const forced = gitArgs.some((arg) => /^(?:-f|--force(?:-with-lease)?(?:=.*)?|--force-if-includes)$/.test(arg));
        const broadPush = gitArgs.some((arg) => /^(?:--all|--mirror|--tags)$/.test(arg));
        const targetsMain = gitArgs.some((arg) => /(?:^|:|\/)(?:main|master)$/.test(arg));
        const sourceMain = gitArgs.some((arg) => /^(?:main|master)(?::|$)/.test(arg));
        if (sub === "push") {
          deny(`Blocked git push: agents may not push, including --all/--mirror/--tags or force pushes. Ask the user to push explicitly.`);
          return;
        }
        if (["commit", "merge", "rebase", "cherry-pick", "revert", "am", "apply", "clean", "rm", "restore", "stash"].includes(sub)) {
          deny(`Blocked git ${sub}: agents may not create, rewrite, delete, or restore repository state. Ask the user explicitly if this operation is required.`);
          return;
        }
        if (["checkout", "switch"].includes(sub)) {
          deny(`Blocked git ${sub}: agents may not change branches or replace working-tree files. The user chooses branch changes.`);
          return;
        }
        const safeGitCommands = new Set([
          "status", "diff", "log", "show", "rev-parse", "ls-files", "grep", "blame",
          "describe", "shortlog", "name-rev", "for-each-ref", "rev-list",
          "merge-base", "cat-file", "count-objects", "fsck", "version", "help", "remote",
        ]);
        if (sub === "remote" && gitArgs.some((arg) => ["add", "remove", "rename", "set-url", "set-head", "prune"].includes(arg))) {
          deny(`Blocked git remote mutation: agents may not change repository remotes.`);
          return;
        }
        if (!safeGitCommands.has(sub)) {
          deny(`Blocked git ${sub}: the command is not on the agent's read-only Git allowlist. Ask the user explicitly if it is required.`);
          return;
        }
      }
    }
  }

  const candidates = [];
  if (pullRequestTool.test(tool) && typeof args.title === "string") {
    candidates.push({ title: args.title, dynamic: false });
  }
  if (isShell) {
    candidates.push(...shellPullRequestTitles(command, tool === "powershell"));
  }

  for (const candidate of candidates) {
    if (candidate.dynamic) {
      deny(`Cannot verify a shell-expanded or auto-filled GitHub PR title. Pass a literal --title value so commitlint can check it.`);
      return;
    }
    const result = await lintTitle(candidate.title);
    if (result.valid) {
      continue;
    }
    if (result.unavailable) {
      deny(`Cannot verify the PR title because commitlint is not installed. Run \`npm ci\` at the repository root, then retry.`);
      return;
    }
    const errors = result.errors?.join("; ") || "title does not satisfy commitlint";
    const types = configuredValues(result.config, "type-enum").join(", ");
    const scopes = configuredValues(result.config, "scope-enum").join(", ");
    deny(`PR title rejected by commitlint: ${errors}. Allowed types: ${types}. Allowed scopes: ${scopes}. Header limit: 100 characters.`);
    return;
  }
}

function changedDocCommentLines(args) {
  if (Array.isArray(args.edits)) {
    return args.edits.flatMap((edit) => (isRecord(edit) ? changedDocCommentLines(edit) : []));
  }
  const oldText = ["old_str", "old_string", "oldString", "old_text", "oldText"]
    .map((key) => args[key])
    .find((value) => typeof value === "string");
  const newText = ["new_str", "new_string", "newString", "new_text", "newText"]
    .map((key) => args[key])
    .find((value) => typeof value === "string");
  if (typeof oldText === "string" && typeof newText === "string") {
    return oldText.split(/\r?\n/)
      .filter((line) => /^\s*(?:\/\/\/|\/\*\*)/.test(line) && !newText.includes(line));
  }

  const patch = patchText(args);
  if (typeof patch !== "string") {
    return [];
  }
  const deleted = patch.split(/\r?\n/)
    .filter((line) => /^-\s*(?:\/\/\/|\/\*\*)/.test(line))
    .map((line) => line.slice(1).trimStart());
  const added = patch.split(/\r?\n/)
    .filter((line) => /^\+\s*(?:\/\/\/|\/\*\*)/.test(line))
    .map((line) => line.slice(1).trimStart());
  return deleted.filter((line) => !added.includes(line));
}

function localePathsFromPatch(patch) {
  if (typeof patch !== "string") {
    return [];
  }
  const paths = [];
  const pattern = /^\*\*\* (?:Update|Add|Delete) File:\s*(.+)$/gm;
  for (const match of patch.matchAll(pattern)) {
    paths.push(match[1].trim());
  }
  return paths;
}

function localeFileForPath(event, filePath) {
  const normalized = normalizedPath(filePath).replace(/^(?:\.\/)+/, "");
  if (!/(?:^|\/)public\/i18n\/(?:en|nl|fr|de)\.json$/i.test(normalized)) {
    return "";
  }
  const base = typeof event.cwd === "string" ? event.cwd : repositoryRoot;
  if (path.isAbsolute(filePath)) {
    return path.resolve(filePath);
  }
  if (/^RefTestManagement\.Ui\/public\/i18n\//i.test(normalized)) {
    return path.resolve(repositoryRoot, normalized);
  }
  if (/^public\/i18n\//i.test(normalized)) {
    const normalizedBase = normalizedPath(base).replace(/\/+$/, "").toLowerCase();
    return normalizedBase.endsWith("/reftestmanagement.ui")
      ? path.resolve(base, normalized)
      : path.resolve(repositoryRoot, "RefTestManagement.Ui", normalized);
  }

  const fromCwd = path.resolve(base, filePath);
  const fromRepository = path.resolve(repositoryRoot, normalized);
  return existsSync(fromCwd) || !existsSync(fromRepository) ? fromCwd : fromRepository;
}

function localeFilesToCheck(event, toolName, args) {
  const tool = toolName.toLowerCase();
  const candidates = [];
  const filePath = getArgumentPath(args);
  if (filePath) {
    candidates.push(filePath);
  }
  candidates.push(...localePathsFromPatch(patchText(args)));

  const command = shellCommandText(args);
  candidates.push(...localePathsFromPatch(command));
  if (shellTools.has(tool) && /(?:public[\\/]i18n|\b(?:en|nl|fr|de)\.json\b)/i.test(command)) {
    for (const locale of ["en", "nl", "fr", "de"]) {
      candidates.push(path.join(repositoryRoot, "RefTestManagement.Ui", "public", "i18n", `${locale}.json`));
    }
  }

  return [...new Set(candidates
    .map((candidate) => localeFileForPath(event, candidate))
    .filter(Boolean))];
}

function validateLocale(filePath) {
  const displayPath = path.relative(repositoryRoot, filePath).replace(/\\/g, "/");
  if (!existsSync(filePath)) {
    return `Locale file ${displayPath} is missing after an edit.`;
  }

  let text;
  try {
    text = readFileSync(filePath, "utf8");
    JSON.parse(text);
  } catch (error) {
    return `Locale file ${displayPath} is not valid JSON (${errorMessage(error)}).`;
  }

  const crlf = (text.match(/\r\n/g) ?? []).length;
  const bareLf = (text.match(/(?<!\r)\n/g) ?? []).length;
  if (crlf > 0 && bareLf > 0) {
    return `Locale file ${displayPath} now mixes CRLF and LF line endings.`;
  }
  if (/(?:^|[\\/])de\.json$/i.test(filePath) && /[^\x00-\x7F]/.test(text)) {
    return `Locale file ${displayPath} contains raw non-ASCII characters, but de.json uses \\u escapes.`;
  }

  const lines = text.split(/\r?\n/);
  const indented = lines.filter((line) => line.trim().length > 0 && /^ +\S/.test(line));
  if (lines.length < 3) {
    return `Locale file ${displayPath} is no longer multiline.`;
  }
  if (!indented.some((line) => /^ {2}\S/.test(line))
    || indented.some((line) => /^ +\S/.test(line) && (line.match(/^ */)?.[0].length ?? 0) % 2 !== 0)
    || lines.some((line) => /^\t+\S/.test(line))) {
    return `Locale file ${displayPath} no longer uses consistent two-space indentation.`;
  }
  return "";
}

function postToolUse(event, toolName, args) {
  const warnings = [];
  if (["edit", "multiedit", "apply_patch", "str_replace_editor"].includes(toolName.toLowerCase())
    && changedDocCommentLines(args).length > 0) {
    warnings.push("A tool edit removed XML/JSDoc lines (`///` or `/**`). Check that the documentation remains accurate and was not removed accidentally.");
  }

  for (const filePath of localeFilesToCheck(event, toolName, args)) {
    const warning = validateLocale(filePath);
    if (warning) {
      warnings.push(`${warning} Preserve the file's multiline two-space formatting and de.json's existing \\u escapes; run npm run check:i18n.`);
    }
  }

  if (warnings.length > 0) {
    addContext(warnings.join("\n"));
  }
}

async function main() {
  const action = process.argv[2];
  try {
    const event = await readEvent();
    if (!providerFlag) {
      provider = "toolName" in event || "toolArgs" in event ? "copilot" : "claude";
    }
    const toolName = getToolName(event);
    const args = getToolArguments(event);

    if (action === "pre") {
      await preToolUse(event, toolName, args);
    } else if (action === "post") {
      postToolUse(event, toolName, args);
    }
  } catch (error) {
    const message = `[ai guard] Could not process hook input; denying the tool call: ${errorMessage(error)}`;
    if (action === "pre") {
      deny(message);
    } else {
      process.stderr.write(`${message}\n`);
    }
  }
}

await main();
