subscription RefTestsUpdated {
  refTestsUpdated {
    __typename
    ... on RefTestStarted {
      id
      status
      startedAt
    }
    ... on RefTestCompleted {
      id
      status
      completedAt
      questionScore
      questionTotal
      answerScore
      answerTotal
      percentage
      language
    }
    ... on RefTestExpired {
      id
      status
    }
    ... on RefTestInvitationSent {
      id
    }
    ... on RefTestResultSent {
      id
    }
    ... on RefTestDeleted {
      id
      status
    }
    ... on RefTestReset {
      id
      oldStatus
    }
    ... on RefTestRevived {
      id
    }
    ... on RefTestCreated {
      id
      name
      email
      titleId
      titleValue
      invitationSent
      resultsSent
      sendInvitationsAutomatically
      sendResultsAutomatically
      status
      numberOfQuestions
      maxTimeInMinutes
    }
  }
}
