subscription RefTestUpdated($id: ID!) {
  refTestUpdated(id: $id) {
    __typename
    ... on RefTestStarted {
      id
      status
      startedAt
    }
    ... on RefTestCompleted {
      id
      status
      completedAt
      questionScore
      questionTotal
      answerScore
      answerTotal
      percentage
      language
    }
    ... on RefTestExpired {
      id
      status
    }
    ... on RefTestInvitationSent {
      id
    }
    ... on RefTestResultSent {
      id
    }
    ... on RefTestDeleted {
      id
    }
    ... on RefTestAnonymized {
      id
      status
      name
      email
    }
    ... on RefTestReset {
      id
      oldStatus
    }
    ... on RefTestRevived {
      id
    }
    ... on RefTestCreated {
      id
    }
    ... on RefTestApproved {
      id
      status
      approvedAt
    }
    ... on RefTestRejected {
      id
      status
      reason
      rejectedAt
    }
  }
}
