<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Handball.Belgium.RefTestManagement.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\RefTestManagement.Domain\RefTestManagement.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="StrawberryShake.Server" Version="15.1.12" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    </ItemGroup>
</Project>


