query GetRefTestsAllCounts(
  $allWhere: RefTestFilterInput
  $pendingWhere: RefTestFilterInput
  $inProgressWhere: RefTestFilterInput
  $completedWhere: RefTestFilterInput
  $expiredWhere: RefTestFilterInput
  $pendingApprovalWhere: RefTestFilterInput
  $rejectedWhere: RefTestFilterInput
) {
  all: refTests(first: 0, where: $allWhere) {
    totalCount
  }
  pending: refTests(first: 0, where: $pendingWhere) {
    totalCount
  }
  inProgress: refTests(first: 0, where: $inProgressWhere) {
    totalCount
  }
  completed: refTests(first: 0, where: $completedWhere) {
    totalCount
  }
  expired: refTests(first: 0, where: $expiredWhere) {
    totalCount
  }
  pendingApproval: refTests(first: 0, where: $pendingApprovalWhere) {
    totalCount
  }
  rejected: refTests(first: 0, where: $rejectedWhere) {
    totalCount
  }
}
