query GetRefTestById($id: ID!) {
  refTest(id: $id) {
    __typename
    ... on RefTest {
      id
      title {
        id
        value
      }
      firstName
      lastName
      name
      email
      invitationSent
      resultsSent
      sendInvitationsAutomatically
      sendResultsAutomatically
      status
      numberOfQuestions
      maxTimeInMinutes
      startedAt
      completedAt
      questionScore
      answerScore
      questionTotal
      answerTotal
      percentage
      selectedAnswerIds
      questions(includeNumber: true, includeIsCorrect: true, randomAnswerOrder: false) {
        id
        number
        phrase
        answers {
          id
          number
          phrase
          isCorrect
        }
      }
      language
    }
    ... on RefTestNotFoundError {
      message
    }
  }
}
