query GetRefTests(
  $first: Int
  $after: String
  $where: RefTestFilterInput
  $order: [RefTestSortInput!]
) {
  refTests(first: $first, after: $after, where: $where, order: $order) {
    edges {
      cursor
      node {
        id
        title {
          id
          value
        }
        firstName
        lastName
        name
        email
        invitationSent
        resultsSent
        sendInvitationsAutomatically
        sendResultsAutomatically
        status
        createdAt
        numberOfQuestions
        maxTimeInMinutes
        scheduledAt
        startedAt
        completedAt
        questionScore
        answerScore
        questionTotal
        answerTotal
        percentage
        language
        rejectionReason
        isAnonymized
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
