schema {
  query: Query
}

type Query {
  "Fetches an object given its ID."
  node("ID of the object." id: ID!): Node
  "Lookup nodes by a list of IDs."
  nodes("The list of node IDs." ids: [ID!]!): [Node]!
  "IHF answers of the game"
  answers(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    "Get answers in random order"
    random: Boolean! = false
    where: AnswerFilterInput
    order: [AnswerSortInput!]
  ): AnswerConnection!
  "IHF answer by id"
  answerById(id: ID!): Answer
  "IHF answers by ids"
  answersById(ids: [ID!]!): [Answer]!
  languages: [String!]!
  "IHF questions of the game"
  questions(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    "Get questions in random order"
    random: Boolean! = false
    where: QuestionFilterInput
    order: [QuestionSortInput!]
  ): QuestionConnection!
  "IHF question by id"
  questionById(id: ID!): Question
  "IHF questions by ids"
  questionsById(ids: [ID!]!): [Question]!
  "IHF question by number"
  questionByNumber(number: String!): Question
  "IHF questions by numbers"
  questionsByNumber(numbers: [String!]!): [Question]!
  "IHF Rules of the game"
  rules(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    "Get rules in random order"
    random: Boolean! = false
    where: RuleFilterInput
    order: [RuleSortInput!]
  ): RuleConnection!
  "IHF rule by id"
  ruleById(id: ID!): Rule
  "IHF rules by ids"
  rulesById(ids: [ID!]!): [Rule]!
  "IHF rule by number"
  ruleByNumber(number: String!): Rule
  "IHF rules by numbers"
  rulesByNumber(numbers: [String!]!): [Rule]!
  scoreConfiguration: ScoreConfiguration!
  "Count the score for your questions based on the given answers"
  calculateScore(
    "Answered questions"
    questionIds: [ID]
    "Selected answers"
    selectedAnswerIds: [ID]
    "Optional score configuration overrides"
    scoreConfigurationInput: ScoreConfigurationInput
  ): Score!
  version: String
  "Version translations for all other languages"
  versions: Any
}

"A connection to a list of items."
type AnswerConnection {
  "A list of edges."
  edges: [AnswerEdge!]
  "A flattened list of the nodes"
  nodes: [Answer!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

"A connection to a list of items."
type QuestionConnection {
  "A list of edges."
  edges: [QuestionEdge!]
  "A flattened list of the nodes"
  nodes: [Question!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

"A connection to a list of items."
type RuleConnection {
  "A list of edges."
  edges: [RuleEdge!]
  "A flattened list of the nodes"
  nodes: [Rule!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int!
}

type AnswerEdge {
  "The item at the end of the edge."
  node: Answer!
  "A cursor for use in pagination."
  cursor: String!
}

type QuestionEdge {
  "The item at the end of the edge."
  node: Question!
  "A cursor for use in pagination."
  cursor: String!
}

type RuleEdge {
  "The item at the end of the edge."
  node: Rule!
  "A cursor for use in pagination."
  cursor: String!
}

"Filter answers based on Id, Name, Number or if the answer is correct"
input AnswerFilterInput {
  and: [AnswerFilterInput!]
  or: [AnswerFilterInput!]
  "Filter on answer id"
  id: UuidOperationFilterInput
  "Filter on answer number"
  number: StringOperationFilterInput
}

"Sort answers based on Id, Name, Number or if the answer is correct"
input AnswerSortInput {
  "Sort on answer id"
  id: SortEnumType
  "Sort on answer number"
  number: SortEnumType
}

"Filter questions based on Id, Name or Number"
input QuestionFilterInput {
  and: [QuestionFilterInput!]
  or: [QuestionFilterInput!]
  "Filter on question id"
  id: UuidOperationFilterInput
  "Filter on question number"
  number: StringOperationFilterInput
}

"Sort questions based on Id, Phrase or Number"
input QuestionSortInput {
  "Sort on question id"
  id: SortEnumType
  "Sort on question number"
  number: SortEnumType
}

"Filter rules based on Id, Name or Number"
input RuleFilterInput {
  and: [RuleFilterInput!]
  or: [RuleFilterInput!]
  "Filter on rule id"
  id: UuidOperationFilterInput
  "Filter on rule number"
  number: StringOperationFilterInput
}

"Sort rules based on Id, Name or Number"
input RuleSortInput {
  "Sort on rule id"
  id: SortEnumType
  "Sort on rule number"
  number: SortEnumType
}

"IHF answer"
type Answer implements Node {
  "The unique identifier of the answer"
  id: ID!
  "The answer phrase based on the \"Accept-Language\" HTTP header"
  phrase: String
  "True if this is a correct answer, false if not"
  isCorrect: Boolean!
  "The question of this answer"
  question: Question
  "Answer translations"
  translations: Any
  "The number of the answer"
  number: String!
  "The id of the question"
  questionId: ID!
}

"IHF question"
type Question implements Node {
  "The unique identifier of the question"
  id: ID!
  "The question phrase based on the \"Accept-Language\" HTTP header"
  phrase: String
  "Question answers"
  answers(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    "Get answers in random order"
    random: Boolean! = false
    where: AnswerFilterInput
    order: [AnswerSortInput!]
  ): AnswerConnection!
  "The rule of this question"
  rule: Rule
  "Question translations"
  translations: Any
  "The number of the question"
  number: String!
  "The id of the rule"
  ruleId: ID!
}

"IHF rule"
type Rule implements Node {
  "The unique identifier of the rule"
  id: ID!
  "The name of the rule based on the \"Accept-Language\" HTTP header"
  name: String
  "Rule questions"
  questions(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    "Get questions in random order"
    random: Boolean! = false
    where: QuestionFilterInput
    order: [QuestionSortInput!]
  ): QuestionConnection!
  "Rule translations"
  translations: Any
  "The number of the rule"
  number: String!
}

"Score calculation"
type Score {
  "Your percentage score"
  percentage: String
  "Your score"
  score: Int!
  "Total number of questions"
  total: Int!
  "The question ids that are not fully correct"
  wrongQuestionsIds: [ID!]!
  "The answer ids that are not correct answered"
  wrongAnswerIds: [ID!]!
}

"The `Any` scalar type represents any valid GraphQL value."
scalar Any

input UuidOperationFilterInput {
  eq: UUID
  neq: UUID
  in: [UUID]
  nin: [UUID]
  gt: UUID
  ngt: UUID
  gte: UUID
  ngte: UUID
  lt: UUID
  nlt: UUID
  lte: UUID
  nlte: UUID
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String
  neq: String
  contains: String
  ncontains: String
  in: [String]
  nin: [String]
  startsWith: String
  nstartsWith: String
  endsWith: String
  nendsWith: String
}

enum SortEnumType {
  ASC
  DESC
}

"The node interface is implemented by entities that have a global unique identifier."
interface Node {
  id: ID!
}

"The `UUID` scalar type represents a Universally Unique Identifier (UUID) as defined by RFC 9562."
scalar UUID

type ScoreConfiguration {
  correct: Int!
  inCorrect: Int!
  notAnswered: Int!
  negativeScore: Boolean!
  penalizeGuessingStrategy: Boolean!
}

input ScoreConfigurationInput {
  correct: Int
  inCorrect: Int
  notAnswered: Int
  negativeScore: Boolean
  penalizeGuessingStrategy: Boolean
}

"Information about pagination in a connection."
type PageInfo {
  "Indicates whether more edges exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more edges exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
  "When paginating backwards, the cursor to continue."
  startCursor: String
  "When paginating forwards, the cursor to continue."
  endCursor: String
  "A list of cursors to continue paginating forwards."
  forwardCursors: [PageCursor!]!
  "A list of cursors to continue paginating backwards."
  backwardCursors: [PageCursor!]!
}

scalar FieldSelectionSet

"A cursor that points to a specific page."
type PageCursor {
  "The page number."
  page: Int!
  "The cursor."
  cursor: String!
}

enum ScalarSerializationType {
  STRING
  BOOLEAN
  INT
  FLOAT
  OBJECT
  LIST
}

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"The purpose of the `@listSize` directive is to either inform the static analysis about the size of returned lists (if that information is statically available), or to point the analysis to where to find that information."
directive @listSize(
  "The `assumedSize` argument can be used to statically define the maximum length of a list returned by a field."
  assumedSize: Int
  "The `slicingArguments` argument can be used to define which of the field's arguments with numeric type are slicing arguments, so that their value determines the size of the list returned by that field. It may specify a list of multiple slicing arguments."
  slicingArguments: [String!]
  "The `slicingArgumentDefaultValue` argument can be used to define a default value for a slicing argument, which is used if the argument is not present in a query."
  slicingArgumentDefaultValue: Int
  "The `sizedFields` argument can be used to define that the value of the `assumedSize` argument or of a slicing argument does not affect the size of a list returned by a field itself, but that of a list returned by one of its sub-fields."
  sizedFields: [String!]
  "The `requireOneSlicingArgument` argument can be used to inform the static analysis that it should expect that exactly one of the defined slicing arguments is present in a query. If that is not the case (i.e., if none or multiple slicing arguments are present), the static analysis may throw an error."
  requireOneSlicingArgument: Boolean = true
) on FIELD_DEFINITION

"The @key directive is used to designate an entity's unique key,\nwhich identifies how to uniquely reference an instance of\nan entity across different source schemas."
directive @key("The field selection set syntax." fields: FieldSelectionSet!) repeatable on
  | OBJECT
  | INTERFACE

"The @lookup directive is used within a source schema to specify output fields\nthat can be used by the distributed GraphQL executor to resolve an entity by\na stable key."
directive @lookup on FIELD_DEFINITION

directive @shareable repeatable on OBJECT | FIELD_DEFINITION

directive @serializeAs(
  "The primitive type a scalar is serialized to."
  type: [ScalarSerializationType!]!
  "The ECMA-262 regex pattern that the serialized scalar value conforms to."
  pattern: String
) on SCALAR