import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const packageJson = JSON.parse(readFileSync(join(__dirname, '..', 'package.json'), 'utf8'));
const versionFilePath = join(__dirname, '..', 'src', 'environments', 'version.ts');

const versionFileContent = `// This file is auto-generated by scripts/generate-version.mjs
export const VERSION = '${packageJson.version}';
`;

mkdirSync(dirname(versionFilePath), { recursive: true });
writeFileSync(versionFilePath, versionFileContent);

console.log(`Version ${packageJson.version} written to ${versionFilePath}`);
