<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Handball.Belgium.RefTestManagement.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" />
        <PackageReference Include="HotChocolate.Abstractions" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
        <PackageReference Include="QuestPDF" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\RefTestManagement.Application\RefTestManagement.Application.csproj" />
        <ProjectReference Include="..\RefTestManagement.AuditLog\RefTestManagement.AuditLog.csproj" />
    </ItemGroup>

</Project>