<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Handball.Belgium.RefTestManagement.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.105.0" />
      <PackageReference Include="HotChocolate.Abstractions" Version="15.1.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
        <PackageReference Include="QuestPDF" Version="2026.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RefTestManagement.Application\RefTestManagement.Application.csproj" />
    </ItemGroup>

</Project>
