<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>8d0886dd-8107-4fe0-9f5a-9526b2cb0681</UserSecretsId>
        <RootNamespace>Handball.Belgium.RefTestManagement.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RefTestManagement.Infrastructure\RefTestManagement.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="15.1.11" />
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="15.1.11"/>
        <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.11"/>
        <PackageReference Include="HotChocolate.Data.EntityFramework" Version="15.1.11"/>
        <PackageReference Include="HotChocolate.Types.Analyzers" Version="15.1.11"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>
