<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>8d0886dd-8107-4fe0-9f5a-9526b2cb0681</UserSecretsId>
        <RootNamespace>Handball.Belgium.RefTestManagement.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RefTestManagement.AuditLog\RefTestManagement.AuditLog.csproj" />
        <ProjectReference Include="..\RefTestManagement.Auth0\RefTestManagement.Auth0.csproj" />
        <ProjectReference
            Include="..\RefTestManagement.Infrastructure\RefTestManagement.Infrastructure.csproj" />
        <ProjectReference
            Include="..\RefTestManagement.Migrations.MySQL\RefTestManagement.Migrations.MySQL.csproj" />
        <ProjectReference
            Include="..\RefTestManagement.Migrations.PostgreSQL\RefTestManagement.Migrations.PostgreSQL.csproj" />
        <ProjectReference
            Include="..\RefTestManagement.Migrations.SQLite\RefTestManagement.Migrations.SQLite.csproj" />
        <ProjectReference
            Include="..\RefTestManagement.Migrations.SqlServer\RefTestManagement.Migrations.SqlServer.csproj" />
        <ProjectReference Include="..\RefTestManagement.Security\RefTestManagement.Security.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore.Authorization" />
        <PackageReference Include="HotChocolate.AspNetCore.CommandLine" />
        <PackageReference Include="HotChocolate.AspNetCore" />
        <PackageReference Include="HotChocolate.Caching" />
        <PackageReference Include="HotChocolate.Data.EntityFramework" />
        <PackageReference Include="HotChocolate.Types.Analyzers" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

</Project>