query GetRefTestByToken($token: String!) {
  refTestByToken(token: $token) {
    __typename
    ... on RefTest {
      id
      name
      email
      numberOfQuestions
      maxTimeInMinutes
      status
      currentQuestionIndex
      questionScore
      questionTotal
      answerScore
      answerTotal
      percentage
      sendResultsAutomatically
    }
    ... on RefTestNotFoundError {
      message
    }
    ... on RefTestExpiredError {
      message
    }
    ... on InvalidRefTestStatusError {
      message
    }
  }
}
