query GetRefTestByToken(
  $token: String!
  $includeQuestionNumbers: Boolean!
  $includeCorrectAnswers: Boolean!
) {
  refTestByToken(token: $token) {
    __typename
    ... on ParticipantRefTest {
      id
      name
      email
      numberOfQuestions
      maxTimeInMinutes
      resultsSent
      status
      currentQuestionIndex
      selectedAnswerIds
      questionScore
      questionTotal
      answerScore
      answerTotal
      percentage
      sendResultsAutomatically
      questions {
        id
        number @include(if: $includeQuestionNumbers)
        phrase
        answers {
          id
          number @include(if: $includeQuestionNumbers)
          phrase
          isCorrect @include(if: $includeCorrectAnswers)
        }
      }
    }
    ... on RefTestNotFoundError {
      message
    }
    ... on RefTestExpiredError {
      message
    }
    ... on InvalidRefTestStatusError {
      message
    }
  }
}
