query GetRefTestByToken($token: String!) {
  refTestByToken(token: $token) {
    __typename
    ... on ParticipantRefTest {
      id
      name
      email
      numberOfQuestions
      maxTimeInMinutes
      resultsSent
      status
      currentQuestionIndex
      selectedAnswerIds
      questionScore
      questionTotal
      answerScore
      answerTotal
      percentage
      sendResultsAutomatically
      questions(includeNumber: true) {
        id
        number
        phrase
        answers {
          id
          number
          phrase
          isCorrect
        }
      }
    }
    ... on RefTestNotFoundError {
      message
    }
    ... on RefTestExpiredError {
      message
    }
    ... on InvalidRefTestStatusError {
      message
    }
  }
}
