<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Handball.Belgium.RefTestManagement.Migrations.SQLite</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference
            Include="..\RefTestManagement.Infrastructure\RefTestManagement.Infrastructure.csproj" />
    </ItemGroup>

</Project>