query getQuestionsById($ids: [ID!]!, $includeNumber: Boolean!, $includeIsCorrect: Boolean!, $randomAnswersOrder: Boolean!) {
    questionsById(ids: $ids) {
        id
        number @include(if: $includeNumber)
        phrase
        translations
        answers(random: $randomAnswersOrder) {
            nodes {
                id
                number @include(if: $includeNumber)
                phrase
                translations
                isCorrect @include(if: $includeIsCorrect)
            }
        }
    }
}