mutation ResetRefTests($input: ResetRefTestsInput!) {
  resetRefTests(input: $input) {
    resetRefTestsResult {
      totalRequested
      successfullyReset
      failed
      resetRefTests {
        id
        status
        createdAt
        invitationSent
        resultsSent
        startedAt
        completedAt
        questionScore
        answerScore
        questionTotal
        answerTotal
        percentage
        selectedAnswerIds
      }
      errors {
        refTestId
        errorMessage
      }
    }
  }
}
