<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.104.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
        <PackageReference Include="QuestPDF" Version="2025.12.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\QuizManagement.Application\QuizManagement.Application.csproj" />
    </ItemGroup>

</Project>
